//! # helix-demo — the synthetic "Alex Rivera" demo dossier
//!
//! ⚠️ **SAMPLE / SYNTHETIC DATA — NOT A REAL PERSON.** ⚠️
//!
//! Everything in this crate is *fiction*. "Alex Rivera" is an invented persona
//! whose numbers were generated by the deterministic functions below — no real
//! health data of any kind was read, copied, or used to build it. It exists so
//! that anyone who clones the **public** Helix repo sees the full product
//! experience (dashboard, score, ask, report, focus areas, bio-age) across all
//! six data domains, with a story that hangs together.
//!
//! It is the source of truth for `ui/demo-dossier.json` (regenerate with
//! `cargo run -p helix-demo --example generate`). The records are real
//! [`ProvRecord`]s, so they flow through the *real* anti-hallucination pipeline
//! (`helix-pipeline::analyze`, `helix-focus`, `helix-score`, `helix-bioage`,
//! `helix-timeline`) — nothing about the demo is mocked. See the tests.
//!
//! ## The persona (fiction)
//! Alex Rivera, ~45, is on a health push. The data tells ONE coherent story:
//! - **Mild iron deficiency** (ferritin low, rechecked, slowly recovering on a
//!   supplement) → the afternoon-fatigue thread.
//! - **Suboptimal deep sleep on late-training nights** (evening strength/cardio
//!   sessions push bedtime late → less deep sleep, lower HRV, higher resting HR).
//! - **Improving body composition on a fitness push** (weight ↓, body-fat ↓,
//!   skeletal muscle ↑, resting HR ↓, steps ↑).
//! - **Borderline lipids** (LDL/ApoB above optimal but improving on lifestyle +
//!   a low-dose statin).
//!
//! All acute/critical markers (potassium, glucose, haemoglobin, SpO₂) sit safely
//! inside range, so the demo shows grounded optimisation answers, not an alarm.
//!
//! Dates are anchored to a fixed reference (2026-06-01) and go back ~90 days, so
//! the demo is fully deterministic and reproducible.

use serde::Serialize;
use serde_json::{json, Value};

use helix_provenance::{Confidence, MeasurementMethod, ProvRecord, RecordId, ReferenceRange};

/// One day in milliseconds.
pub const DAY: i64 = 86_400_000;

/// Fixed reference "now": 2026-06-01T00:00:00Z. All records are dated relative to
/// this so the demo never depends on the wall clock (matches ADR-007's
/// clock-injection discipline). Verified: `Date.UTC(2026, 5, 1) == 1_780_272_000_000`.
pub const ANCHOR_MS: i64 = 1_780_272_000_000;

/// Length of the demo window in days (record dates span `[ANCHOR-89d, ANCHOR]`).
pub const SPAN_DAYS: i64 = 90;

/// The banner that must travel with the demo data everywhere it is shown.
pub const DISCLAIMER: &str = "SAMPLE / SYNTHETIC DATA — NOT A REAL PERSON. \
    'Alex Rivera' is a fictional persona; every value here was generated \
    deterministically for demonstration only and must never be read as medical fact.";

// ---------------------------------------------------------------------------
// Deterministic pseudo-randomness (dependency-free, reproducible).
// ---------------------------------------------------------------------------

/// SplitMix64 — a tiny, well-mixed hash so per-day jitter is reproducible.
fn hash64(mut x: u64) -> u64 {
    x = x.wrapping_add(0x9E37_79B9_7F4A_7C15);
    x = (x ^ (x >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    x = (x ^ (x >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    x ^ (x >> 31)
}

/// Reproducible jitter in `[-amp, amp]` from a metric salt and a day index.
fn jitter(salt: u64, day: i64, amp: f64) -> f64 {
    if amp == 0.0 {
        return 0.0;
    }
    let h = hash64(salt ^ (day as u64).wrapping_mul(0x1000_0001B3));
    let u = (h as f64) / (u64::MAX as f64); // [0,1]
    (u * 2.0 - 1.0) * amp
}

fn round_to(v: f64, decimals: u32) -> f64 {
    let f = 10f64.powi(decimals as i32);
    (v * f).round() / f
}

/// Timestamp for `days_before` the anchor (`0` == anchor / most recent).
fn day_ms(days_before: i64) -> i64 {
    ANCHOR_MS - days_before * DAY
}

/// Progress through the window: `0.0` at the oldest day, `1.0` at the anchor.
fn progress(days_before: i64) -> f64 {
    (SPAN_DAYS - 1 - days_before) as f64 / (SPAN_DAYS - 1) as f64
}

fn lerp(start: f64, end: f64, p: f64) -> f64 {
    start + (end - start) * p
}

/// Program day-of-week (0..6) for a given `days_before` — drives the training
/// schedule and the "late-night workout hurts deep sleep" correlation.
fn program_dow(days_before: i64) -> i64 {
    (SPAN_DAYS - 1 - days_before).rem_euclid(7)
}

/// Late (evening) training nights: Tue (dow 2) & Fri (dow 5). These nights get a
/// deep-sleep / HRV penalty in the wearable series — the encoded correlation.
fn is_late_training(days_before: i64) -> bool {
    matches!(program_dow(days_before), 2 | 5)
}

// ---------------------------------------------------------------------------
// Record builder.
// ---------------------------------------------------------------------------

#[allow(clippy::too_many_arguments)]
fn rec(
    id: String,
    source: &str,
    measured_at: i64,
    method: MeasurementMethod,
    code: Option<&str>,
    concept: &str,
    value: f64,
    unit: &str,
    low: Option<f64>,
    high: Option<f64>,
    confidence: f64,
) -> ProvRecord {
    let reference_range = if low.is_some() || high.is_some() {
        Some(ReferenceRange::new(low, high))
    } else {
        None
    };
    ProvRecord {
        id: RecordId::from(id),
        source: source.to_string(),
        measured_at,
        method,
        code: code.map(|c| c.to_string()),
        concept: concept.to_string(),
        value,
        unit: unit.to_string(),
        reference_range,
        confidence: Confidence::new(confidence),
    }
}

// ---------------------------------------------------------------------------
// Domain 1 (part) + wearable daily series (Apple Watch / Apple Health).
// ---------------------------------------------------------------------------

/// A daily-sampled metric with a gentle start→end trend plus reproducible jitter.
struct Daily {
    id_prefix: &'static str,
    code: &'static str,
    concept: &'static str,
    unit: &'static str,
    source: &'static str,
    method: MeasurementMethod,
    start: f64,
    end: f64,
    amp: f64,
    /// Delta applied on late-training nights (negative = worse recovery).
    late_delta: f64,
    low: Option<f64>,
    high: Option<f64>,
    /// Hard clamp applied after jitter (keeps e.g. SpO₂ safely above red-flags).
    clamp: Option<(f64, f64)>,
    decimals: u32,
    salt: u64,
}

fn daily_series(m: &Daily, out: &mut Vec<ProvRecord>) {
    for d in (0..SPAN_DAYS).rev() {
        // d = days before anchor; iterate oldest → newest for readable ids.
        let p = progress(d);
        let mut v = lerp(m.start, m.end, p) + jitter(m.salt, d, m.amp);
        if m.late_delta != 0.0 && is_late_training(d) {
            v += m.late_delta;
        }
        if let Some((lo, hi)) = m.clamp {
            v = v.clamp(lo, hi);
        }
        out.push(rec(
            format!("{}-{}", m.id_prefix, d),
            m.source,
            day_ms(d),
            m.method,
            Some(m.code),
            m.concept,
            round_to(v, m.decimals),
            m.unit,
            m.low,
            m.high,
            0.95,
        ));
    }
}

fn wearable_metrics() -> Vec<Daily> {
    use MeasurementMethod::Device;
    vec![
        Daily {
            id_prefix: "ah-sleep-dur",
            code: "HK-SLEEP-DUR",
            concept: "Sleep duration",
            unit: "min",
            source: "Apple Watch",
            method: Device,
            start: 430.0,
            end: 452.0,
            amp: 12.0,
            late_delta: -35.0,
            low: None,
            high: None,
            clamp: Some((300.0, 540.0)),
            decimals: 0,
            salt: 0xA1,
        },
        Daily {
            id_prefix: "ah-sleep-deep",
            code: "HK-SLEEP-DEEP",
            concept: "Deep sleep",
            unit: "min",
            source: "Apple Watch",
            method: Device,
            start: 68.0,
            end: 92.0,
            amp: 7.0,
            late_delta: -24.0,
            low: None,
            high: None,
            clamp: Some((25.0, 140.0)),
            decimals: 0,
            salt: 0xA2,
        },
        Daily {
            id_prefix: "ah-sleep-rem",
            code: "HK-SLEEP-REM",
            concept: "REM sleep",
            unit: "min",
            source: "Apple Watch",
            method: Device,
            start: 84.0,
            end: 100.0,
            amp: 9.0,
            late_delta: -12.0,
            low: None,
            high: None,
            clamp: Some((30.0, 150.0)),
            decimals: 0,
            salt: 0xA3,
        },
        Daily {
            id_prefix: "ah-rhr",
            code: "HK-RHR",
            concept: "Resting heart rate",
            unit: "beats/min",
            source: "Apple Watch",
            method: Device,
            start: 60.0,
            end: 54.0,
            amp: 1.5,
            late_delta: 4.0,
            low: Some(40.0),
            high: Some(100.0),
            clamp: Some((44.0, 80.0)),
            decimals: 0,
            salt: 0xA4,
        },
        Daily {
            id_prefix: "ah-hrv",
            code: "HK-HRV",
            concept: "Heart rate variability (SDNN)",
            unit: "ms",
            source: "Apple Watch",
            method: Device,
            start: 42.0,
            end: 58.0,
            amp: 3.5,
            late_delta: -9.0,
            low: None,
            high: None,
            clamp: Some((20.0, 120.0)),
            decimals: 0,
            salt: 0xA5,
        },
        Daily {
            id_prefix: "ah-steps",
            code: "HK-STEPS",
            concept: "Steps",
            unit: "count",
            source: "Apple Watch",
            method: Device,
            start: 6800.0,
            end: 10200.0,
            amp: 1400.0,
            late_delta: 0.0,
            low: None,
            high: None,
            clamp: Some((1500.0, 20000.0)),
            decimals: 0,
            salt: 0xA6,
        },
        // SpO₂ carries the escalation LOINC (59408-5); clamped well above the
        // 90%/88% red-flag bounds so the demo never spuriously escalates.
        Daily {
            id_prefix: "ah-spo2",
            code: "59408-5",
            concept: "Oxygen saturation (SpO₂)",
            unit: "%",
            source: "Apple Watch",
            method: Device,
            start: 96.5,
            end: 97.6,
            amp: 0.6,
            late_delta: 0.0,
            low: Some(95.0),
            high: Some(100.0),
            clamp: Some((95.5, 99.0)),
            decimals: 0,
            salt: 0xA7,
        },
    ]
}

fn workouts(out: &mut Vec<ProvRecord>) {
    for d in (0..SPAN_DAYS).rev() {
        let (name, base, salt) = match program_dow(d) {
            0 => ("Zone 2 run", 52.0, 0xB0u64), // Sun long easy run (AM)
            2 => ("Strength — full body", 50.0, 0xB2), // Tue (evening / late)
            4 => ("Strength — upper/lower", 46.0, 0xB4), // Thu (AM)
            5 => ("Zone 2 cycling", 56.0, 0xB5), // Fri (evening / late)
            _ => continue,
        };
        let mins = round_to(base + jitter(salt, d, 6.0), 0);
        out.push(rec(
            format!("ah-workout-{d}"),
            "Apple Watch",
            day_ms(d),
            MeasurementMethod::Device,
            Some("HK-WORKOUT"),
            &format!("Workout — {name}"),
            mins,
            "min",
            None,
            None,
            0.95,
        ));
    }
}

// ---------------------------------------------------------------------------
// Domain 2: Lose It — daily calories + macros.
// ---------------------------------------------------------------------------

fn nutrition_metrics() -> Vec<Daily> {
    use MeasurementMethod::ManualEntry;
    vec![
        Daily {
            id_prefix: "li-kcal",
            code: "LOSEIT-KCAL",
            concept: "Energy intake",
            unit: "kcal",
            source: "Lose It",
            method: ManualEntry,
            start: 2500.0,
            end: 2320.0,
            amp: 170.0,
            late_delta: 0.0,
            low: None,
            high: None,
            clamp: Some((1600.0, 3200.0)),
            decimals: 0,
            salt: 0xC1,
        },
        Daily {
            id_prefix: "li-protein",
            code: "LOSEIT-PROTEIN",
            concept: "Protein intake",
            unit: "g",
            source: "Lose It",
            method: ManualEntry,
            start: 118.0,
            end: 168.0,
            amp: 14.0,
            late_delta: 0.0,
            low: None,
            high: None,
            clamp: Some((70.0, 230.0)),
            decimals: 0,
            salt: 0xC2,
        },
        Daily {
            id_prefix: "li-carb",
            code: "LOSEIT-CARB",
            concept: "Carbohydrate intake",
            unit: "g",
            source: "Lose It",
            method: ManualEntry,
            start: 265.0,
            end: 232.0,
            amp: 28.0,
            late_delta: 0.0,
            low: None,
            high: None,
            clamp: Some((120.0, 400.0)),
            decimals: 0,
            salt: 0xC3,
        },
        Daily {
            id_prefix: "li-fat",
            code: "LOSEIT-FAT",
            concept: "Fat intake",
            unit: "g",
            source: "Lose It",
            method: ManualEntry,
            start: 92.0,
            end: 82.0,
            amp: 9.0,
            late_delta: 0.0,
            low: None,
            high: None,
            clamp: Some((40.0, 140.0)),
            decimals: 0,
            salt: 0xC4,
        },
    ]
}

// ---------------------------------------------------------------------------
// Domain 3: RENPHO smart-scale — ~50-metric body-composition panel, every 3 days.
// ---------------------------------------------------------------------------

/// (id, code, concept, unit, start, end, amp, decimals, low, high)
type Renpho = (
    &'static str,
    &'static str,
    &'static str,
    &'static str,
    f64,
    f64,
    f64,
    u32,
    Option<f64>,
    Option<f64>,
);

fn renpho_panel() -> Vec<Renpho> {
    vec![
        (
            "rp-weight",
            "RENPHO-WEIGHT",
            "Weight",
            "kg",
            82.0,
            79.4,
            0.4,
            1,
            None,
            None,
        ),
        (
            "rp-bmi",
            "RENPHO-BMI",
            "Body mass index",
            "kg/m2",
            25.3,
            24.5,
            0.15,
            1,
            None,
            None,
        ),
        (
            "rp-bfp",
            "RENPHO-BFP",
            "Body fat",
            "%",
            22.6,
            18.9,
            0.5,
            1,
            None,
            None,
        ),
        (
            "rp-fatmass",
            "RENPHO-FATMASS",
            "Fat mass",
            "kg",
            18.5,
            15.0,
            0.4,
            1,
            None,
            None,
        ),
        (
            "rp-smm",
            "RENPHO-SMM",
            "Skeletal muscle mass",
            "kg",
            33.4,
            35.7,
            0.3,
            1,
            None,
            None,
        ),
        (
            "rp-muscle",
            "RENPHO-MUSCLE",
            "Muscle mass",
            "kg",
            60.0,
            62.6,
            0.4,
            1,
            None,
            None,
        ),
        (
            "rp-water",
            "RENPHO-WATER",
            "Body water",
            "%",
            54.8,
            58.4,
            0.5,
            1,
            None,
            None,
        ),
        (
            "rp-waterkg",
            "RENPHO-WATERKG",
            "Body water mass",
            "kg",
            44.9,
            46.3,
            0.4,
            1,
            None,
            None,
        ),
        (
            "rp-visceral",
            "RENPHO-VISCERAL",
            "Visceral fat rating",
            "rating",
            9.0,
            7.0,
            0.3,
            0,
            None,
            Some(10.0),
        ),
        (
            "rp-bone",
            "RENPHO-BONE",
            "Bone mass",
            "kg",
            3.10,
            3.22,
            0.05,
            2,
            None,
            None,
        ),
        (
            "rp-bmr",
            "RENPHO-BMR",
            "Basal metabolic rate",
            "kcal",
            1720.0,
            1762.0,
            18.0,
            0,
            None,
            None,
        ),
        (
            "rp-proteinpct",
            "RENPHO-PROTEINPCT",
            "Protein",
            "%",
            17.4,
            18.6,
            0.3,
            1,
            None,
            None,
        ),
        (
            "rp-metage",
            "RENPHO-METAGE",
            "Metabolic age",
            "years",
            47.0,
            41.0,
            0.6,
            0,
            None,
            None,
        ),
        (
            "rp-subq",
            "RENPHO-SUBQ",
            "Subcutaneous fat",
            "%",
            19.2,
            16.1,
            0.4,
            1,
            None,
            None,
        ),
        (
            "rp-lbm",
            "RENPHO-LBM",
            "Lean body mass",
            "kg",
            63.5,
            64.4,
            0.4,
            1,
            None,
            None,
        ),
        (
            "rp-musclerate",
            "RENPHO-MUSCLERATE",
            "Muscle rate",
            "%",
            73.2,
            75.8,
            0.4,
            1,
            None,
            None,
        ),
        (
            "rp-ffm",
            "RENPHO-FFM",
            "Fat-free body weight",
            "kg",
            63.5,
            64.4,
            0.4,
            1,
            None,
            None,
        ),
        (
            "rp-smr",
            "RENPHO-SMR",
            "Skeletal muscle rate",
            "%",
            40.7,
            44.9,
            0.4,
            1,
            None,
            None,
        ),
        (
            "rp-obesity",
            "RENPHO-OBESITY",
            "Obesity degree",
            "%",
            5.0,
            -1.0,
            0.6,
            1,
            None,
            None,
        ),
        (
            "rp-bodyscore",
            "RENPHO-BODYSCORE",
            "Body score",
            "score",
            78.0,
            85.0,
            1.2,
            0,
            None,
            None,
        ),
        (
            "rp-trunkfatpct",
            "RENPHO-TRUNKFATPCT",
            "Trunk fat",
            "%",
            21.0,
            18.0,
            0.4,
            1,
            None,
            None,
        ),
        (
            "rp-larmfatpct",
            "RENPHO-LARMFATPCT",
            "Left arm fat",
            "%",
            18.0,
            15.0,
            0.4,
            1,
            None,
            None,
        ),
        (
            "rp-rarmfatpct",
            "RENPHO-RARMFATPCT",
            "Right arm fat",
            "%",
            18.5,
            15.4,
            0.4,
            1,
            None,
            None,
        ),
        (
            "rp-llegfatpct",
            "RENPHO-LLEGFATPCT",
            "Left leg fat",
            "%",
            20.0,
            17.0,
            0.4,
            1,
            None,
            None,
        ),
        (
            "rp-rlegfatpct",
            "RENPHO-RLEGFATPCT",
            "Right leg fat",
            "%",
            20.2,
            17.1,
            0.4,
            1,
            None,
            None,
        ),
        (
            "rp-trunkmus",
            "RENPHO-TRUNKMUS",
            "Trunk muscle mass",
            "kg",
            28.0,
            29.2,
            0.3,
            1,
            None,
            None,
        ),
        (
            "rp-larmmus",
            "RENPHO-LARMMUS",
            "Left arm muscle mass",
            "kg",
            3.40,
            3.72,
            0.06,
            2,
            None,
            None,
        ),
        (
            "rp-rarmmus",
            "RENPHO-RARMMUS",
            "Right arm muscle mass",
            "kg",
            3.50,
            3.82,
            0.06,
            2,
            None,
            None,
        ),
        (
            "rp-llegmus",
            "RENPHO-LLEGMUS",
            "Left leg muscle mass",
            "kg",
            9.60,
            10.10,
            0.10,
            2,
            None,
            None,
        ),
        (
            "rp-rlegmus",
            "RENPHO-RLEGMUS",
            "Right leg muscle mass",
            "kg",
            9.70,
            10.20,
            0.10,
            2,
            None,
            None,
        ),
        (
            "rp-trunkfatkg",
            "RENPHO-TRUNKFATKG",
            "Trunk fat mass",
            "kg",
            9.8,
            8.0,
            0.2,
            1,
            None,
            None,
        ),
        (
            "rp-larmfatkg",
            "RENPHO-LARMFATKG",
            "Left arm fat mass",
            "kg",
            0.62,
            0.50,
            0.03,
            2,
            None,
            None,
        ),
        (
            "rp-rarmfatkg",
            "RENPHO-RARMFATKG",
            "Right arm fat mass",
            "kg",
            0.64,
            0.52,
            0.03,
            2,
            None,
            None,
        ),
        (
            "rp-llegfatkg",
            "RENPHO-LLEGFATKG",
            "Left leg fat mass",
            "kg",
            2.30,
            1.95,
            0.05,
            2,
            None,
            None,
        ),
        (
            "rp-rlegfatkg",
            "RENPHO-RLEGFATKG",
            "Right leg fat mass",
            "kg",
            2.33,
            1.98,
            0.05,
            2,
            None,
            None,
        ),
        (
            "rp-subqmass",
            "RENPHO-SUBQMASS",
            "Subcutaneous fat mass",
            "kg",
            15.8,
            12.8,
            0.3,
            1,
            None,
            None,
        ),
        (
            "rp-viscarea",
            "RENPHO-VISCFATAREA",
            "Visceral fat area",
            "cm2",
            92.0,
            72.0,
            3.0,
            0,
            None,
            None,
        ),
        (
            "rp-fmi",
            "RENPHO-FMI",
            "Fat mass index",
            "kg/m2",
            5.7,
            4.6,
            0.1,
            1,
            None,
            None,
        ),
        (
            "rp-ffmi",
            "RENPHO-FFMI",
            "Fat-free mass index",
            "kg/m2",
            19.6,
            19.9,
            0.1,
            1,
            None,
            None,
        ),
        (
            "rp-smi",
            "RENPHO-SMI",
            "Skeletal muscle index",
            "kg/m2",
            7.4,
            7.9,
            0.1,
            1,
            None,
            None,
        ),
        (
            "rp-proteinmass",
            "RENPHO-PROTEINMASS",
            "Protein mass",
            "kg",
            14.3,
            14.8,
            0.1,
            1,
            None,
            None,
        ),
        (
            "rp-mineral",
            "RENPHO-MINERAL",
            "Mineral mass",
            "kg",
            3.35,
            3.42,
            0.03,
            2,
            None,
            None,
        ),
        (
            "rp-cellmass",
            "RENPHO-CELLMASS",
            "Body cell mass",
            "kg",
            33.0,
            34.4,
            0.3,
            1,
            None,
            None,
        ),
        (
            "rp-ecw",
            "RENPHO-ECW",
            "Extracellular water",
            "%",
            43.0,
            42.2,
            0.2,
            1,
            None,
            None,
        ),
        (
            "rp-icw",
            "RENPHO-ICW",
            "Intracellular water",
            "%",
            57.0,
            57.8,
            0.2,
            1,
            None,
            None,
        ),
        (
            "rp-whr",
            "RENPHO-WHR",
            "Waist-hip ratio",
            "ratio",
            0.90,
            0.86,
            0.01,
            2,
            None,
            None,
        ),
        (
            "rp-stdweight",
            "RENPHO-STDWEIGHT",
            "Standard (ideal) weight",
            "kg",
            72.0,
            72.0,
            0.0,
            1,
            None,
            None,
        ),
        (
            "rp-weightctrl",
            "RENPHO-WEIGHTCTRL",
            "Weight control (to ideal)",
            "kg",
            10.0,
            7.4,
            0.2,
            1,
            None,
            None,
        ),
        (
            "rp-fatctrl",
            "RENPHO-FATCTRL",
            "Fat control",
            "kg",
            -6.0,
            -3.0,
            0.2,
            1,
            None,
            None,
        ),
        (
            "rp-musclectrl",
            "RENPHO-MUSCLECTRL",
            "Muscle control",
            "kg",
            1.5,
            0.4,
            0.1,
            1,
            None,
            None,
        ),
        (
            "rp-heartrate",
            "RENPHO-HEARTRATE",
            "Scale heart rate",
            "beats/min",
            62.0,
            57.0,
            2.0,
            0,
            None,
            None,
        ),
    ]
}

fn renpho_records(out: &mut Vec<ProvRecord>) {
    let panel = renpho_panel();
    for d in (0..SPAN_DAYS).rev() {
        if d % 3 != 0 {
            continue; // full body-comp scan every 3 days
        }
        let p = progress(d);
        for (i, m) in panel.iter().enumerate() {
            let (id, code, concept, unit, start, end, amp, dec, low, high) = *m;
            let salt = 0xD000 ^ (i as u64);
            let v = lerp(start, end, p) + jitter(salt, d, amp);
            out.push(rec(
                format!("{id}-{d}"),
                "RENPHO",
                day_ms(d),
                MeasurementMethod::Device,
                Some(code),
                concept,
                round_to(v, dec),
                unit,
                low,
                high,
                0.9,
            ));
        }
    }
}

// ---------------------------------------------------------------------------
// Domain 5: Quest Diagnostics labs — two draws (a couple of markers rechecked).
// ---------------------------------------------------------------------------

/// (loinc, concept, unit, low, high, draw-A value, optional draw-B value)
type Lab = (
    &'static str,
    &'static str,
    &'static str,
    Option<f64>,
    Option<f64>,
    f64,
    Option<f64>,
);

const DRAW_A: i64 = 85; // annual physical
const DRAW_B: i64 = 8; // 12-week recheck

fn lab_panel() -> Vec<Lab> {
    vec![
        // CBC
        (
            "718-7",
            "Hemoglobin",
            "g/dL",
            Some(13.5),
            Some(17.5),
            13.6,
            Some(13.9),
        ),
        (
            "4544-3",
            "Hematocrit",
            "%",
            Some(41.0),
            Some(50.0),
            40.2,
            Some(41.3),
        ),
        (
            "789-8",
            "Red blood cell count",
            "10*6/uL",
            Some(4.5),
            Some(5.9),
            4.58,
            Some(4.71),
        ),
        (
            "787-2",
            "Mean corpuscular volume (MCV)",
            "fL",
            Some(80.0),
            Some(100.0),
            84.0,
            Some(86.0),
        ),
        (
            "785-6",
            "Mean corpuscular hemoglobin (MCH)",
            "pg",
            Some(27.0),
            Some(33.0),
            27.2,
            Some(28.1),
        ),
        (
            "786-4",
            "MCHC",
            "g/dL",
            Some(32.0),
            Some(36.0),
            33.0,
            Some(33.5),
        ),
        (
            "788-0",
            "Red cell distribution width (RDW)",
            "%",
            Some(11.5),
            Some(14.5),
            14.3,
            Some(13.8),
        ),
        (
            "6690-2",
            "White blood cell count",
            "10*3/uL",
            Some(3.4),
            Some(10.8),
            5.6,
            Some(5.8),
        ),
        (
            "777-3",
            "Platelet count",
            "10*3/uL",
            Some(150.0),
            Some(400.0),
            248.0,
            Some(252.0),
        ),
        (
            "770-8",
            "Neutrophils",
            "%",
            Some(40.0),
            Some(70.0),
            55.0,
            None,
        ),
        (
            "736-9",
            "Lymphocytes",
            "%",
            Some(20.0),
            Some(45.0),
            32.0,
            Some(33.0),
        ),
        // Iron studies (ferritin handled separately with a mid draw)
        (
            "2498-4",
            "Iron",
            "ug/dL",
            Some(65.0),
            Some(175.0),
            45.0,
            Some(68.0),
        ),
        (
            "2500-7",
            "Total iron binding capacity (TIBC)",
            "ug/dL",
            Some(250.0),
            Some(425.0),
            412.0,
            Some(360.0),
        ),
        (
            "2502-3",
            "Transferrin saturation",
            "%",
            Some(20.0),
            Some(50.0),
            11.0,
            Some(18.0),
        ),
        // CMP
        (
            "2345-7",
            "Glucose",
            "mg/dL",
            Some(70.0),
            Some(99.0),
            92.0,
            Some(90.0),
        ),
        (
            "3094-0",
            "Urea nitrogen (BUN)",
            "mg/dL",
            Some(7.0),
            Some(20.0),
            15.0,
            Some(14.0),
        ),
        (
            "2160-0",
            "Creatinine",
            "mg/dL",
            Some(0.7),
            Some(1.3),
            0.95,
            Some(0.93),
        ),
        (
            "62238-1",
            "eGFR",
            "mL/min/1.73m2",
            Some(60.0),
            None,
            95.0,
            Some(96.0),
        ),
        (
            "2951-2",
            "Sodium",
            "mmol/L",
            Some(135.0),
            Some(145.0),
            140.0,
            Some(140.0),
        ),
        (
            "2823-3",
            "Serum potassium",
            "mmol/L",
            Some(3.5),
            Some(5.1),
            4.2,
            Some(4.3),
        ),
        (
            "2075-0",
            "Chloride",
            "mmol/L",
            Some(98.0),
            Some(107.0),
            102.0,
            Some(101.0),
        ),
        (
            "2028-9",
            "Carbon dioxide (CO2)",
            "mmol/L",
            Some(22.0),
            Some(30.0),
            25.0,
            Some(26.0),
        ),
        (
            "17861-6",
            "Calcium",
            "mg/dL",
            Some(8.6),
            Some(10.2),
            9.5,
            Some(9.4),
        ),
        (
            "2885-2",
            "Total protein",
            "g/dL",
            Some(6.0),
            Some(8.3),
            7.0,
            Some(7.1),
        ),
        (
            "1751-7",
            "Albumin",
            "g/dL",
            Some(3.5),
            Some(5.0),
            4.6,
            Some(4.7),
        ),
        (
            "1975-2",
            "Total bilirubin",
            "mg/dL",
            Some(0.1),
            Some(1.2),
            0.6,
            Some(0.6),
        ),
        (
            "6768-6",
            "Alkaline phosphatase",
            "U/L",
            Some(40.0),
            Some(129.0),
            68.0,
            Some(70.0),
        ),
        (
            "1920-8",
            "AST",
            "U/L",
            Some(10.0),
            Some(40.0),
            24.0,
            Some(23.0),
        ),
        (
            "1742-6",
            "ALT",
            "U/L",
            Some(7.0),
            Some(56.0),
            28.0,
            Some(25.0),
        ),
        // Lipids
        (
            "2093-3",
            "Total cholesterol",
            "mg/dL",
            None,
            Some(200.0),
            205.0,
            Some(198.0),
        ),
        (
            "13457-7",
            "LDL cholesterol (calc)",
            "mg/dL",
            None,
            Some(100.0),
            135.0,
            Some(128.0),
        ),
        (
            "2085-9",
            "HDL cholesterol",
            "mg/dL",
            Some(40.0),
            None,
            52.0,
            Some(55.0),
        ),
        (
            "2571-8",
            "Triglycerides",
            "mg/dL",
            None,
            Some(150.0),
            160.0,
            Some(140.0),
        ),
        (
            "1884-6",
            "Apolipoprotein B",
            "mg/dL",
            None,
            Some(90.0),
            105.0,
            Some(98.0),
        ),
        // Other
        (
            "1989-3",
            "Vitamin D (25-OH)",
            "ng/mL",
            Some(30.0),
            Some(100.0),
            24.0,
            Some(31.0),
        ),
        ("30522-7", "hs-CRP", "mg/L", None, Some(3.0), 1.8, Some(1.1)),
        (
            "4548-4",
            "Hemoglobin A1c",
            "%",
            Some(4.0),
            Some(5.6),
            5.4,
            Some(5.3),
        ),
        (
            "3016-3",
            "TSH",
            "mIU/L",
            Some(0.4),
            Some(4.0),
            2.1,
            Some(2.0),
        ),
    ]
}

fn lab_records(out: &mut Vec<ProvRecord>) {
    for (loinc, concept, unit, low, high, a, b) in lab_panel() {
        out.push(rec(
            format!("lab-{loinc}-A"),
            "Quest Diagnostics",
            day_ms(DRAW_A),
            MeasurementMethod::LabFeed,
            Some(loinc),
            concept,
            a,
            unit,
            low,
            high,
            1.0,
        ));
        if let Some(bv) = b {
            out.push(rec(
                format!("lab-{loinc}-B"),
                "Quest Diagnostics",
                day_ms(DRAW_B),
                MeasurementMethod::LabFeed,
                Some(loinc),
                concept,
                bv,
                unit,
                low,
                high,
                1.0,
            ));
        }
    }
    // Ferritin: low → rechecked twice, slowly recovering on iron (still marginal).
    for (id, day, val) in [
        ("lab-2276-4-A", DRAW_A, 22.0),
        ("lab-2276-4-mid", 40, 26.0),
        ("lab-2276-4-B", DRAW_B, 29.0),
    ] {
        out.push(rec(
            id.to_string(),
            "Quest Diagnostics",
            day_ms(day),
            MeasurementMethod::LabFeed,
            Some("2276-4"),
            "Ferritin",
            val,
            "ng/mL",
            Some(30.0),
            Some(400.0),
            1.0,
        ));
    }
}

// ---------------------------------------------------------------------------
// Domain 4: Pharmacy — active medication list (RxNorm ingredient codes).
// ---------------------------------------------------------------------------

/// Active medications as provenance records (kept separate from analysable vitals
/// so a dose is never trended like a lab value). RxNorm codes are ingredient-level
/// (stable CUIs); the dose lives in the concept + value.
fn medications() -> Vec<ProvRecord> {
    let started = day_ms(DRAW_A - 1); // filled the day after the physical
    vec![
        rec(
            "rx-ferrous-sulfate".into(),
            "CVS Pharmacy",
            started,
            MeasurementMethod::LabFeed,
            Some("4009"),
            "Ferrous sulfate 325 mg oral tablet — 1 tab daily (iron deficiency)",
            325.0,
            "mg",
            None,
            None,
            1.0,
        ),
        rec(
            "rx-atorvastatin".into(),
            "CVS Pharmacy",
            started,
            MeasurementMethod::LabFeed,
            Some("83367"),
            "Atorvastatin 10 mg oral tablet — 1 tab nightly (borderline LDL/ApoB)",
            10.0,
            "mg",
            None,
            None,
            1.0,
        ),
        rec(
            "rx-cholecalciferol".into(),
            "CVS Pharmacy",
            started,
            MeasurementMethod::LabFeed,
            Some("2418"),
            "Cholecalciferol (vitamin D3) 2000 IU oral — 1 daily (vitamin D insufficiency)",
            2000.0,
            "[IU]",
            None,
            None,
            1.0,
        ),
    ]
}

// ---------------------------------------------------------------------------
// Domain 6: EMR — plain-language clinician visit notes.
// ---------------------------------------------------------------------------

#[derive(Serialize)]
struct Note {
    date_ms: i64,
    author: &'static str,
    source: &'static str,
    kind: &'static str,
    text: &'static str,
}

fn notes() -> Vec<Note> {
    vec![
        Note {
            date_ms: day_ms(DRAW_A),
            author: "Dr. Priya Nguyen, MD",
            source: "Helix Family Medicine (EMR)",
            kind: "Annual physical",
            text: "45 y/o presents for annual visit, reports several months of afternoon fatigue with \
                otherwise reasonable diet and activity. Exam unremarkable, vitals normal. Ordered CBC, \
                iron studies, CMP, lipid panel, HbA1c, vitamin D, TSH, hs-CRP. Results show ferritin low \
                at 22 with low iron saturation (11%) and low-normal hemoglobin — consistent with early \
                iron deficiency without anemia, a plausible driver of the fatigue. Vitamin D insufficient \
                (24). LDL and ApoB borderline elevated; HbA1c and TSH normal. Plan: start ferrous sulfate \
                325 mg daily with vitamin C, cholecalciferol 2000 IU daily, low-dose atorvastatin 10 mg for \
                the lipid picture. Discussed a strength + Zone-2 cardio program and higher dietary protein. \
                Recheck iron studies and lipids in ~12 weeks.",
        },
        Note {
            date_ms: day_ms(DRAW_B),
            author: "Dr. Priya Nguyen, MD",
            source: "Helix Family Medicine (EMR)",
            kind: "12-week recheck",
            text: "Iron-studies and lipid recheck. Ferritin improved 22 → 29 (still marginally low), iron \
                saturation 11 → 18%, hemoglobin 13.6 → 13.9. Reports afternoon energy better on most days, \
                but notably worse the mornings after late evening workouts, which also show shorter deep \
                sleep on his watch data. Body composition improving on the program (body fat ~22% → ~19%, \
                weight down ~2.5 kg, resting HR trending down). Lipids improving: LDL 135 → 128, ApoB 105 → \
                98 — continue atorvastatin and lifestyle, recheck in 3 months. Vitamin D 24 → 31 — continue \
                D3. Counseled to shift weeknight training earlier to protect deep sleep. Continue iron; \
                recheck ferritin in 8-10 weeks.",
        },
    ]
}

// ---------------------------------------------------------------------------
// Score subsystems, ask questions, timeline, bio-age inputs.
// ---------------------------------------------------------------------------

fn subsystems() -> Value {
    json!([
        { "subsystem": "cardiometabolic", "value": 72, "weight": 0.35, "confidence": 0.85, "trend": "improving", "driver": "LDL/ApoB borderline (improving), HDL ok, HbA1c 5.3%", "color": "#34e0c4" },
        { "subsystem": "sleep", "value": 76, "weight": 0.25, "confidence": 0.80, "trend": "improving", "driver": "Deep sleep & HRV up — but dip on late-training nights", "color": "#38bdf8" },
        { "subsystem": "inflammation", "value": 80, "weight": 0.20, "confidence": 0.85, "trend": "stable", "driver": "hs-CRP 1.1 mg/L, ferritin recovering", "color": "#9b8cff" },
        { "subsystem": "fitness", "value": 74, "weight": 0.20, "confidence": 0.70, "trend": "improving", "driver": "Resting HR ↓, body fat ↓, muscle ↑, steps ↑", "color": "#f6a623" }
    ])
}

fn questions() -> Value {
    json!([
        { "label": "Why am I tired in the afternoons?", "code": "2276-4", "lo": 30, "hi": 400, "flat_band_per_day": 0.02, "flat_band_frac": 0.0 },
        { "label": "How are my lipids trending?", "code": "13457-7", "lo": null, "hi": 100, "flat_band_per_day": 0.02, "flat_band_frac": 0.0 },
        { "label": "Is my deep sleep improving?", "code": "HK-SLEEP-DEEP", "lo": null, "hi": null, "flat_band_per_day": 0.05, "flat_band_frac": 0.0 },
        { "label": "What about my testosterone?", "code": "2986-8", "lo": 300, "hi": 1000, "flat_band_per_day": 0.02, "flat_band_frac": 0.0 }
    ])
}

/// Improving score arc with a clear lift when the fitness push began (~day 55).
fn timeline() -> Value {
    json!([
        { "days_before": 88, "value": 68 },
        { "days_before": 74, "value": 68 },
        { "days_before": 60, "value": 69 },
        { "days_before": 46, "value": 72 },
        { "days_before": 32, "value": 73 },
        { "days_before": 16, "value": 74 },
        { "days_before": 0, "value": 75 }
    ])
}

/// PhenoAge inputs derived from Alex's most-recent (draw B) labs, in the units
/// helix-bioage expects. Age 45.
fn bioage_inputs() -> Value {
    json!({
        "albumin_g_l": 47.0,        // 4.7 g/dL
        "creatinine_umol_l": 82.0,  // 0.93 mg/dL × 88.4
        "glucose_mmol_l": 5.0,      // 90 mg/dL ÷ 18
        "crp_mg_dl": 0.11,          // 1.1 mg/L ÷ 10
        "lymphocyte_pct": 33.0,
        "mcv_fl": 86.0,
        "rdw_pct": 13.8,
        "alk_phosphatase_u_l": 70.0,
        "wbc_1000_ul": 5.8,
        "age_years": 45.0
    })
}

// ---------------------------------------------------------------------------
// Public API.
// ---------------------------------------------------------------------------

/// Every analysable record across the wearable, nutrition, body-composition and
/// lab domains (medications and clinician notes are surfaced separately). These
/// are canonical [`ProvRecord`]s and are what flow through the real pipeline.
pub fn records() -> Vec<ProvRecord> {
    let mut out = Vec::new();
    for m in wearable_metrics() {
        daily_series(&m, &mut out);
    }
    workouts(&mut out);
    for m in nutrition_metrics() {
        daily_series(&m, &mut out);
    }
    renpho_records(&mut out);
    lab_records(&mut out);
    out
}

/// Per-domain record counts (for the manifest / reporting).
pub fn domain_counts() -> Value {
    let all = records();
    let count = |src: &str| all.iter().filter(|r| r.source == src).count();
    json!({
        "apple_health": count("Apple Watch"),
        "lose_it": count("Lose It"),
        "renpho": count("RENPHO"),
        "quest_labs": count("Quest Diagnostics"),
        "pharmacy": medications().len(),
        "emr_notes": notes().len(),
        "total_records": all.len(),
    })
}

/// Assemble the full demo dossier the UI/mobile consume as JSON.
pub fn dossier() -> Value {
    let recs = records();
    let meds = medications();
    json!({
        "meta": {
            "disclaimer": DISCLAIMER,
            "synthetic": true,
            "persona": {
                "name": "Alex Rivera",
                "age": 45,
                "sex": "unspecified",
                "summary": "Fictional 45-year-old on a health push: mild iron deficiency (recovering \
                    on a supplement) behind afternoon fatigue, improving body composition and resting \
                    HR from a strength + Zone-2 program, deep sleep that dips on late-training nights, \
                    and borderline lipids trending back toward target."
            },
            "anchor_date": "2026-06-01",
            "generated_by": "helix-demo (cargo run -p helix-demo --example generate)",
            "domains": domain_counts()
        },
        "now": ANCHOR_MS,
        "records": recs,
        "medications": meds,
        "notes": notes(),
        "subsystems": subsystems(),
        "questions": questions(),
        "timeline": timeline(),
        "bioage_inputs": bioage_inputs()
    })
}

/// Serialize the dossier as pretty JSON (what `ui/demo-dossier.json` holds).
pub fn dossier_json_pretty() -> String {
    serde_json::to_string_pretty(&dossier()).expect("dossier serializes")
}

#[cfg(test)]
mod tests {
    use super::*;
    use helix_bioage::phenoage;
    use helix_escalation::{builtin_registry_v1, EscalationLevel};
    use helix_focus::{select_focus, FocusConfig, FocusReason};
    use helix_numeric::TrendDirection;
    use helix_pipeline::{analyze, AnalyzeRequest, AnswerOutcome};
    use helix_provenance::ProvRecord;
    use helix_score::{compose, Driver, SubScore, Subsystem, Trend};

    fn recs_for(all: &[ProvRecord], code: &str) -> Vec<ProvRecord> {
        all.iter()
            .filter(|r| r.code.as_deref() == Some(code))
            .cloned()
            .collect()
    }

    #[test]
    fn dates_are_anchored_and_in_window() {
        let all = records();
        assert!(!all.is_empty());
        for r in &all {
            assert!(
                r.measured_at <= ANCHOR_MS,
                "no record is in the future of the anchor"
            );
            assert!(
                r.measured_at >= ANCHOR_MS - (SPAN_DAYS) * DAY,
                "within the ~90-day window"
            );
        }
    }

    #[test]
    fn every_record_is_schema_complete() {
        for r in records() {
            assert!(!r.source.is_empty());
            assert!(!r.concept.is_empty());
            assert!(!r.unit.is_empty());
            assert!(r.value.is_finite());
            assert!((0.0..=1.0).contains(&r.confidence.get()));
        }
    }

    #[test]
    fn ferritin_flows_through_pipeline_grounded_and_recovering() {
        let all = records();
        let ferr = recs_for(&all, "2276-4");
        assert_eq!(
            ferr.len(),
            3,
            "three ferritin draws (low → rechecked twice)"
        );
        let req = AnalyzeRequest {
            concept_code: "2276-4",
            records: &ferr,
            now: ANCHOR_MS,
            staleness_window_days: 365,
            confidence_floor: 0.5,
            reference_low: Some(30.0),
            reference_high: Some(400.0),
            flat_band_per_day: 0.02,
            flat_band_frac: 0.0,
        };
        let AnswerOutcome::Answered(ans) = analyze(&req, &builtin_registry_v1()).unwrap() else {
            panic!("ferritin should produce a grounded answer, not an abstention");
        };
        // Recovering (rising) but the claim is grounded in all three real records.
        assert_eq!(ans.trend.direction, TrendDirection::Rising);
        assert_eq!(ans.trend.sample_size, 3);
        assert_eq!(ans.claims.len(), 1);
        assert_eq!(ans.claims[0].evidence().len(), 3);
        assert_eq!(ans.escalation.level, EscalationLevel::None);
        assert!(ans.recommendation.is_some());
    }

    #[test]
    fn deep_sleep_wearable_trend_is_grounded_and_rising() {
        let all = records();
        let deep = recs_for(&all, "HK-SLEEP-DEEP");
        assert!(deep.len() >= 80, "roughly daily deep-sleep readings");
        let req = AnalyzeRequest {
            concept_code: "HK-SLEEP-DEEP",
            records: &deep,
            now: ANCHOR_MS,
            staleness_window_days: 365,
            confidence_floor: 0.5,
            reference_low: None,
            reference_high: None,
            flat_band_per_day: 0.05,
            flat_band_frac: 0.0,
        };
        let AnswerOutcome::Answered(ans) = analyze(&req, &builtin_registry_v1()).unwrap() else {
            panic!("deep sleep should answer");
        };
        assert_eq!(ans.trend.direction, TrendDirection::Rising);
    }

    #[test]
    fn testosterone_question_honestly_abstains() {
        let all = records();
        let t = recs_for(&all, "2986-8");
        assert!(t.is_empty(), "we deliberately hold no testosterone data");
        let req = AnalyzeRequest {
            concept_code: "2986-8",
            records: &t,
            now: ANCHOR_MS,
            staleness_window_days: 365,
            confidence_floor: 0.5,
            reference_low: Some(300.0),
            reference_high: Some(1000.0),
            flat_band_per_day: 0.02,
            flat_band_frac: 0.0,
        };
        assert!(matches!(
            analyze(&req, &builtin_registry_v1()).unwrap(),
            AnswerOutcome::Abstained(_)
        ));
    }

    #[test]
    fn focus_surfaces_the_iron_and_lipid_story() {
        let all = records();
        let focus = select_focus(&all, ANCHOR_MS, &FocusConfig::default());
        let concepts: Vec<&str> = focus.iter().map(|f| f.concept.as_str()).collect();
        assert!(
            concepts.contains(&"Ferritin"),
            "ferritin below range is flagged"
        );
        assert!(
            concepts.contains(&"LDL cholesterol (calc)"),
            "borderline LDL is flagged"
        );
        // Ferritin is below range → OutOfRange (recovering, so not 'worsening').
        let ferr = focus.iter().find(|f| f.concept == "Ferritin").unwrap();
        assert_eq!(ferr.reason, FocusReason::OutOfRange);
    }

    #[test]
    fn no_record_trips_a_red_flag_escalation() {
        // Every record whose code is in the escalation registry must be safe, so
        // the demo shows optimisation guidance rather than an alarm.
        let reg = builtin_registry_v1();
        for r in records() {
            if let Some(code) = &r.code {
                if let Some(_t) = reg.get(code) {
                    let res = reg.evaluate(code, r.value).unwrap();
                    assert_eq!(
                        res.level,
                        EscalationLevel::None,
                        "{} = {} should be safe",
                        r.concept,
                        r.value
                    );
                }
            }
        }
    }

    #[test]
    fn subsystems_compose_to_a_believable_score() {
        // Mirror the JS wiring: build SubScores from the subsystem manifest.
        let subs = vec![
            SubScore {
                subsystem: Subsystem::Cardiometabolic,
                value: 72.0,
                weight: 0.35,
                confidence: 0.85,
                drivers: vec![driver("Lipids")],
                trend: Trend::Improving,
            },
            SubScore {
                subsystem: Subsystem::Sleep,
                value: 76.0,
                weight: 0.25,
                confidence: 0.80,
                drivers: vec![driver("Deep sleep")],
                trend: Trend::Improving,
            },
            SubScore {
                subsystem: Subsystem::Inflammation,
                value: 80.0,
                weight: 0.20,
                confidence: 0.85,
                drivers: vec![driver("hs-CRP")],
                trend: Trend::Stable,
            },
            SubScore {
                subsystem: Subsystem::Fitness,
                value: 74.0,
                weight: 0.20,
                confidence: 0.70,
                drivers: vec![driver("Resting HR")],
                trend: Trend::Improving,
            },
        ];
        let score = compose(subs).unwrap();
        assert!(
            (70.0..=80.0).contains(&score.value),
            "score {}",
            score.value
        );
        assert_eq!(score.subscores.len(), 4);
    }

    fn driver(c: &str) -> Driver {
        Driver {
            concept: c.into(),
            points: 75.0,
            trend: Trend::Improving,
            source_record: "rec".into(),
        }
    }

    #[test]
    fn bioage_estimate_is_younger_than_chronological() {
        let i = bioage_inputs();
        let inputs = helix_bioage::PhenoInputs {
            albumin_g_l: i["albumin_g_l"].as_f64().unwrap(),
            creatinine_umol_l: i["creatinine_umol_l"].as_f64().unwrap(),
            glucose_mmol_l: i["glucose_mmol_l"].as_f64().unwrap(),
            crp_mg_dl: i["crp_mg_dl"].as_f64().unwrap(),
            lymphocyte_pct: i["lymphocyte_pct"].as_f64().unwrap(),
            mcv_fl: i["mcv_fl"].as_f64().unwrap(),
            rdw_pct: i["rdw_pct"].as_f64().unwrap(),
            alk_phosphatase_u_l: i["alk_phosphatase_u_l"].as_f64().unwrap(),
            wbc_1000_ul: i["wbc_1000_ul"].as_f64().unwrap(),
            age_years: i["age_years"].as_f64().unwrap(),
        };
        let b = phenoage(&inputs).unwrap();
        assert!(
            b.delta_years < 0.0,
            "healthy labs → younger, delta {}",
            b.delta_years
        );
    }

    #[test]
    fn covers_all_six_domains() {
        let d = domain_counts();
        assert!(d["apple_health"].as_u64().unwrap() > 100);
        assert!(d["lose_it"].as_u64().unwrap() > 100);
        assert!(d["renpho"].as_u64().unwrap() > 100);
        assert!(d["quest_labs"].as_u64().unwrap() > 30);
        assert_eq!(d["pharmacy"].as_u64().unwrap(), 3);
        assert_eq!(d["emr_notes"].as_u64().unwrap(), 2);
    }

    #[test]
    fn dossier_json_is_valid_and_labelled() {
        let s = dossier_json_pretty();
        assert!(s.contains("SAMPLE / SYNTHETIC DATA"));
        assert!(s.contains("Alex Rivera"));
        // round-trips as JSON
        let _v: Value = serde_json::from_str(&s).unwrap();
    }
}
