//! # helix-refranges — population reference intervals (NHANES-derived FALLBACK)
//!
//! Imported values (especially from OCR or CSV) often arrive with **no reference
//! range**, so the focus/trend logic can't tell whether a value is out of range.
//! This crate provides a **labeled fallback**: per-analyte reference intervals
//! derived from **NHANES 2021–2023** (CDC, public domain) — the 2.5th–97.5th
//! percentiles over ~5,600–6,000 U.S. adults.
//!
//! ⚠️ **These are POPULATION percentiles, not lab-specific clinical reference
//! intervals.** Because NHANES is a general population (including people with
//! disease), some intervals are wider than a healthy-cohort clinical range (e.g.
//! glucose/triglycerides/CRP). They are an honest *fallback for orientation*, must
//! be labeled as such in any UI (ADR-006 evidence tiering), and never override a
//! lab's own range when one is supplied. Regenerate:
//! `cargo run -p helix-bioage --example nhanes_refranges`.

use helix_provenance::{RangePosition, ReferenceRange};

/// One population reference interval, keyed by LOINC code.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct RefInterval {
    pub loinc: &'static str,
    pub name: &'static str,
    pub unit: &'static str,
    /// 2.5th percentile (population low).
    pub low: f64,
    /// 97.5th percentile (population high).
    pub high: f64,
    /// Population median (50th percentile).
    pub median: f64,
}

const fn r(
    loinc: &'static str,
    name: &'static str,
    unit: &'static str,
    low: f64,
    high: f64,
    median: f64,
) -> RefInterval {
    RefInterval {
        loinc,
        name,
        unit,
        low,
        high,
        median,
    }
}

/// Provenance string that must accompany any use of these intervals.
pub const SOURCE: &str =
    "Population reference interval (NHANES 2021–2023, 2.5–97.5th pctile, US adults) — \
     a fallback for orientation, not your lab's reference range.";

/// NHANES 2021–2023 population reference intervals (2.5–97.5 pctile, adults 18+).
/// Generated by `helix-bioage` example `nhanes_refranges`.
pub const NHANES_REF: &[RefInterval] = &[
    r("1751-7", "Albumin", "g/dL", 3.3, 4.7, 4.1),
    r("6768-6", "Alkaline phosphatase", "U/L", 45.0, 147.0, 80.0),
    r("1742-6", "ALT", "U/L", 8.0, 60.0, 18.0),
    r("1920-8", "AST", "U/L", 12.0, 47.0, 20.0),
    r("3094-0", "Urea nitrogen (BUN)", "mg/dL", 7.0, 28.0, 14.0),
    r("17861-6", "Calcium", "mg/dL", 8.7, 10.2, 9.4),
    r("2093-3", "Total cholesterol", "mg/dL", 115.0, 278.0, 186.0),
    r("2160-0", "Creatinine", "mg/dL", 0.53, 1.46, 0.85),
    r("2345-7", "Glucose", "mg/dL", 77.0, 204.0, 95.0),
    r("2823-3", "Potassium", "mmol/L", 3.5, 4.8, 4.1),
    r("2951-2", "Sodium", "mmol/L", 134.0, 144.0, 140.0),
    r("2885-2", "Total protein", "g/dL", 6.3, 8.0, 7.1),
    r("2571-8", "Triglycerides", "mg/dL", 45.0, 373.0, 108.0),
    r("3084-1", "Uric acid", "mg/dL", 2.8, 8.3, 5.1),
    r("2498-4", "Iron", "ug/dL", 30.0, 172.0, 85.0),
    r("2777-1", "Phosphorus", "mg/dL", 2.6, 4.5, 3.5),
    r("1975-2", "Total bilirubin", "mg/dL", 0.2, 1.2, 0.4),
    r("6690-2", "White blood cells", "1000/uL", 3.8, 11.8, 6.6),
    r("718-7", "Hemoglobin", "g/dL", 10.8, 16.6, 13.9),
    r("4544-3", "Hematocrit", "%", 32.7, 48.7, 41.2),
    r("787-2", "MCV", "fL", 75.1, 98.7, 89.0),
    r("788-0", "RDW", "%", 12.3, 17.2, 13.6),
    r("777-3", "Platelets", "1000/uL", 148.0, 410.0, 249.0),
    r("736-9", "Lymphocytes", "%", 14.6, 48.3, 29.6),
    r("789-8", "Red blood cells", "million/uL", 3.71, 5.64, 4.64),
    r("1988-5", "hs-CRP", "mg/L", 0.23, 17.63, 1.8),
    r("1558-6", "Fasting glucose", "mg/dL", 83.0, 203.0, 101.0),
];

/// Look up the population reference interval for a LOINC code.
pub fn lookup(loinc: &str) -> Option<&'static RefInterval> {
    NHANES_REF.iter().find(|r| r.loinc == loinc)
}

/// Build a [`ReferenceRange`] fallback for a LOINC code (for records that arrived
/// without one). Returns `None` if the code isn't covered.
pub fn reference_range_for(loinc: &str) -> Option<ReferenceRange> {
    lookup(loinc).map(|r| ReferenceRange::new(Some(r.low), Some(r.high)))
}

/// Classify a value against the population interval for a code (fallback only).
pub fn position_for(loinc: &str, value: f64) -> Option<RangePosition> {
    lookup(loinc).map(|r| {
        if value < r.low {
            RangePosition::Below
        } else if value > r.high {
            RangePosition::Above
        } else {
            RangePosition::Within
        }
    })
}

/// How many analytes the fallback table covers.
pub fn coverage() -> usize {
    NHANES_REF.len()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn covers_common_markers_with_sane_intervals() {
        assert!(coverage() >= 25);
        let cr = lookup("2160-0").unwrap(); // creatinine
        assert_eq!(cr.name, "Creatinine");
        assert!(cr.low < cr.median && cr.median < cr.high);
        assert!((0.4..0.7).contains(&cr.low) && (1.2..1.6).contains(&cr.high));
    }

    #[test]
    fn builds_reference_range_fallback() {
        let rr = reference_range_for("2951-2").unwrap(); // sodium 134–144
        assert_eq!(rr.low, Some(134.0));
        assert_eq!(rr.high, Some(144.0));
        assert!(reference_range_for("0000-0").is_none());
    }

    #[test]
    fn classifies_against_population_interval() {
        assert_eq!(position_for("2160-0", 0.3), Some(RangePosition::Below)); // low creatinine
        assert_eq!(position_for("2160-0", 0.9), Some(RangePosition::Within));
        assert_eq!(position_for("2160-0", 2.0), Some(RangePosition::Above));
        assert_eq!(position_for("nope", 1.0), None);
    }

    #[test]
    fn every_interval_is_ordered_and_labeled() {
        for ri in NHANES_REF {
            assert!(ri.low < ri.median && ri.median <= ri.high, "{}", ri.name);
            assert!(!ri.loinc.is_empty() && !ri.unit.is_empty());
        }
        assert!(SOURCE.contains("NHANES"));
    }
}
