// Helix management console — runs the real Rust anti-hallucination pipeline
// (helix-core/score) compiled to WebAssembly. No business logic is duplicated
// in JS; this file is presentation + wiring only.
import init, {
  analyze_json,
  compose_score_json,
  redflag_registry_version,
  version,
  sensing_reading_json,
  genome_profile_json,
  bioage_json,
  focus_json,
  timeline_json,
  fhir_import_json,
  ocr_ingest_json,
  apple_health_import_json,
  genome_raw_import_json,
  visual_encode_json,
  visual_maxsim_json,
  population_range_json,
} from "./pkg/helix.js";

// previously-encoded image embeddings, for the OCR "looks similar" preview
const visualMemory = [];

const DAY = 86_400_000;

// ---- Demo dossier (the SYNTHETIC "Alex Rivera" persona) --------------------
// Loaded from ./demo-dossier.json — a fully-fictional sample generated by the
// helix-demo Rust crate across all six data domains (Apple Watch, Lose It,
// RENPHO, Quest labs, Pharmacy, EMR). It stands in for the user's decrypted
// vault records and flows through the SAME real WASM pipeline. Not a real person.
let NOW = Date.UTC(2026, 5, 1); // fixed "now" (2026-06-01); overwritten by fixture
let records = [];
let MEDS = [];
let NOTES = [];
let TIMELINE = [];
let BIOAGE = null;
let META = null;
let QUESTIONS = [];
let SUBSYSTEMS = [];

// A tiny fallback so the console still renders if the fixture can't be fetched.
const FALLBACK = {
  now: NOW,
  records: [
    { id: "f1", source: "Quest Diagnostics", measured_at: NOW - 85 * DAY, method: "lab_feed", code: "2276-4", concept: "Ferritin", value: 22, unit: "ng/mL", reference_range: { low: 30, high: 400 }, confidence: 1 },
    { id: "f2", source: "Quest Diagnostics", measured_at: NOW - 40 * DAY, method: "lab_feed", code: "2276-4", concept: "Ferritin", value: 26, unit: "ng/mL", reference_range: { low: 30, high: 400 }, confidence: 1 },
    { id: "f3", source: "Quest Diagnostics", measured_at: NOW - 8 * DAY, method: "lab_feed", code: "2276-4", concept: "Ferritin", value: 29, unit: "ng/mL", reference_range: { low: 30, high: 400 }, confidence: 1 },
  ],
  medications: [], notes: [], timeline: [{ days_before: 0, value: 75 }],
  bioage_inputs: { albumin_g_l: 47, creatinine_umol_l: 82, glucose_mmol_l: 5, crp_mg_dl: 0.11, lymphocyte_pct: 33, mcv_fl: 86, rdw_pct: 13.8, alk_phosphatase_u_l: 70, wbc_1000_ul: 5.8, age_years: 45 },
  questions: [
    { label: "Why am I tired in the afternoons?", code: "2276-4", lo: 30, hi: 400, flat_band_per_day: 0.02, flat_band_frac: 0 },
    { label: "What about my testosterone?", code: "2986-8", lo: 300, hi: 1000, flat_band_per_day: 0.02, flat_band_frac: 0 },
  ],
  subsystems: [
    { subsystem: "cardiometabolic", value: 72, weight: 0.35, confidence: 0.85, trend: "improving", driver: "Lipids", color: "#34e0c4" },
    { subsystem: "sleep", value: 76, weight: 0.25, confidence: 0.8, trend: "improving", driver: "Deep sleep, HRV", color: "#38bdf8" },
    { subsystem: "inflammation", value: 80, weight: 0.2, confidence: 0.85, trend: "stable", driver: "hs-CRP, ferritin", color: "#9b8cff" },
    { subsystem: "fitness", value: 74, weight: 0.2, confidence: 0.7, trend: "improving", driver: "Resting HR, body fat", color: "#f6a623" },
  ],
  meta: { persona: { name: "Alex Rivera (fallback)" }, disclaimer: "SAMPLE / SYNTHETIC DATA — not a real person." },
};

function applyDossier(d) {
  NOW = d.now;
  records = d.records;
  MEDS = d.medications || [];
  NOTES = d.notes || [];
  TIMELINE = d.timeline || [];
  BIOAGE = d.bioage_inputs;
  META = d.meta || null;
  QUESTIONS = d.questions || [];
  SUBSYSTEMS = d.subsystems || [];
}

async function loadDossier() {
  try {
    const res = await fetch("./demo-dossier.json", { cache: "no-cache" });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    applyDossier(await res.json());
  } catch (e) {
    console.warn("demo-dossier.json unavailable, using fallback:", e.message);
    applyDossier(FALLBACK);
  }
  renderDemoBanner();
}

// Persona + "synthetic data" disclaimer banner.
function renderDemoBanner() {
  const el = document.getElementById("demo-banner");
  if (!el || !META) return;
  const name = META.persona?.name || "Sample persona";
  const n = records.length + MEDS.length;
  el.innerHTML = `<b>SAMPLE DATA</b> · <b>${name}</b> — a fully synthetic demo persona
    (${n.toLocaleString()} records across 6 sources). Not a real person; every value is fictional.`;
  el.hidden = false;
}

let score = null;

async function boot() {
  const pill = document.getElementById("engine-pill");
  try {
    await init();
    pill.classList.add("ready");
    document.getElementById("engine-text").textContent =
      `engine v${version()} · ${redflag_registry_version()}`;
  } catch (e) {
    pill.classList.add("err");
    document.getElementById("engine-text").textContent = "engine failed";
    console.error(e);
    return;
  }
  await loadDossier();
  computeScore();
  renderDashboard();
  renderAskChips();
  renderRecords();
  renderSources();
  renderReport();
  wireNav();
  wireModals();
  wireImport();

  // Deep-link hooks (used for headless screenshot capture & shareable states).
  const h = location.hash;
  if (h === "#ask") {
    document.querySelector('.nav-item[data-view="ask"]').click();
    runAsk();
  } else if (h === "#guide") {
    openModal(guideModal());
  } else if (h === "#sensing") {
    document.querySelector('.nav-item[data-view="sources"]').click();
    runSensingDemo();
  } else if (h === "#genome") {
    document.querySelector('.nav-item[data-view="sources"]').click();
    runGenomeDemo();
  } else if (h === "#report") {
    document.querySelector('.nav-item[data-view="report"]').click();
  } else if (h === "#import") {
    document.querySelector('.nav-item[data-view="import"]').click();
  } else if (h === "#import-demo") {
    document.querySelector('.nav-item[data-view="import"]').click();
    importFhir(SAMPLE_FHIR);
    importCsv(SAMPLE_CSV);
    importApple(SAMPLE_APPLE, "export.xml");
    importGenome(SAMPLE_GENOME, "23andMe-v5.txt");
  }
}

// ---- Score (real compose() in wasm) ----
function computeScore() {
  const subs = SUBSYSTEMS.map((s) => ({
    subsystem: s.subsystem, value: s.value, weight: s.weight, confidence: s.confidence,
    trend: s.trend,
    drivers: [{ concept: s.driver, points: s.value, trend: s.trend, source_record: "rec" }],
  }));
  score = JSON.parse(compose_score_json(JSON.stringify(subs)));
}

function renderDashboard() {
  document.getElementById("score-value").textContent = Math.round(score.value);
  const off = 327 - (327 * score.value) / 100;
  document.getElementById("ring-fg").style.strokeDashoffset = off;
  const t = { improving: "▲ improving", stable: "→ holding steady", worsening: "▼ slipping" };
  document.getElementById("score-trend").textContent =
    `${t[overallTrend()] || ""} · confidence ${Math.round(score.confidence * 100)}%`;

  const sys = document.getElementById("systems");
  sys.innerHTML = "";
  SUBSYSTEMS.forEach((s) => {
    const el = document.createElement("div");
    el.className = "system";
    el.innerHTML = `<div class="s-top"><span class="s-name">${cap(s.subsystem)}</span>
      <span class="s-val">${s.value}</span></div>
      <div class="s-bar"><i style="width:${s.value}%;background:${s.color}"></i></div>`;
    el.onclick = () => openSystemModal(s);
    sys.appendChild(el);
  });

  renderTwin();
  renderBriefing();
}

// Status colour for a sub-score (schematic, from the user's own data — ADR-015).
function statusColor(v) {
  if (v >= 80) return "#34d399"; // good
  if (v >= 65) return "#f6a623"; // watch
  return "#fb7185"; // attention
}

// Anatomical digital twin — organ dots coloured by the real subsystem scores.
function renderTwin() {
  const byKey = Object.fromEntries(SUBSYSTEMS.map((s) => [s.subsystem, s]));
  // organ → subsystem mapping + position on the silhouette
  const organs = [
    { sys: "sleep", cx: 100, cy: 40, r: 11, label: "Brain · sleep" },
    { sys: "cardiometabolic", cx: 90, cy: 96, r: 12, label: "Heart · cardiometabolic" },
    { sys: "inflammation", cx: 112, cy: 120, r: 11, label: "Gut · inflammation" },
    { sys: "fitness", cx: 100, cy: 168, r: 11, label: "Legs · fitness" },
  ];
  const dots = organs
    .map((o) => {
      const s = byKey[o.sys];
      const c = statusColor(s.value);
      return `<g class="organ" data-sys="${o.sys}">
        <circle class="halo" cx="${o.cx}" cy="${o.cy}" r="${o.r + 8}" fill="${c}"></circle>
        <circle cx="${o.cx}" cy="${o.cy}" r="${o.r}" fill="${c}"></circle></g>`;
    })
    .join("");
  document.getElementById("twin").innerHTML = `
    <svg viewBox="0 0 200 230" role="img" aria-label="Body systems map">
      <circle cx="100" cy="28" r="16" class="body-stroke"/>
      <path d="M78 52 Q100 46 122 52 L130 138 Q100 150 70 138 Z" class="body-stroke"/>
      <g class="limb">
        <path d="M80 58 L54 120"/><path d="M120 58 L146 120"/>
        <path d="M86 146 L80 210"/><path d="M114 146 L120 210"/>
      </g>
      ${dots}
    </svg>
    <div class="twin-legend">
      <span><i style="background:#34d399"></i>good</span>
      <span><i style="background:#f6a623"></i>watch</span>
      <span><i style="background:#fb7185"></i>attention</span>
    </div>`;
  document.querySelectorAll("#twin .organ").forEach((g) => {
    g.onclick = () => {
      const s = SUBSYSTEMS.find((x) => x.subsystem === g.dataset.sys);
      openSystemModal(s);
    };
  });
}

// Dynamic "Today" briefing — the real grounded insight from the pipeline.
function renderBriefing() {
  const q = QUESTIONS[0]; // ferritin (afternoon-fatigue thread)
  if (!q) { document.getElementById("briefing").textContent = "Reading your dossier…"; return; }
  const out = JSON.parse(
    analyze_json(
      JSON.stringify({
        concept_code: q.code,
        records: records.filter((r) => r.code === q.code),
        now: NOW, staleness_window_days: 365, confidence_floor: 0.5,
        reference_low: q.lo, reference_high: q.hi,
        flat_band_per_day: q.flat_band_per_day ?? 0.02, flat_band_frac: q.flat_band_frac ?? 0,
      })
    )
  );
  const el = document.getElementById("briefing");
  if (out.outcome === "answered" && out.claims?.length) {
    const tr = out.trend;
    const dirWord = { rising: "slowly recovering", falling: "still trending down", flat: "holding steady" }[tr.direction] || tr.direction;
    const e = out.claims[0].evidence[out.claims[0].evidence.length - 1];
    const belowRange = e.reference_range && e.reference_range.low != null && e.value < e.reference_range.low;
    el.innerHTML = `${belowRange ? "Low ferritin may be behind your afternoon energy dips" : "Your ferritin looks on track"} —
      it's ${e.value} ${e.unit} and ${dirWord}.
      <span class="b-cite">${e.concept} ${e.value} ${e.unit} · ${e.source}</span>
      <span class="b-act" id="brief-ask">See the full answer →</span>`;
    document.getElementById("brief-ask").onclick = () => {
      document.querySelector('.nav-item[data-view="ask"]').click();
      runAsk();
    };
  } else {
    el.textContent = "Everything looks steady today.";
  }
}

function overallTrend() {
  const w = { improving: 0, stable: 0, worsening: 0 };
  SUBSYSTEMS.forEach((s) => (w[s.trend] += s.weight));
  return Object.entries(w).sort((a, b) => b[1] - a[1])[0][0];
}

// ---- Ask (real analyze() in wasm) ----
function renderAskChips() {
  const box = document.getElementById("ask-chips");
  box.innerHTML = "";
  QUESTIONS.forEach((q, i) => {
    const b = document.createElement("button");
    b.className = "ask-chip" + (i === 0 ? " sel" : "");
    b.textContent = q.label;
    b.onclick = () => {
      [...box.children].forEach((c) => c.classList.remove("sel"));
      b.classList.add("sel");
      box.dataset.sel = i;
    };
    box.appendChild(b);
  });
  box.dataset.sel = 0;
  document.getElementById("run-ask").onclick = runAsk;
}

function runAsk() {
  const q = QUESTIONS[+document.getElementById("ask-chips").dataset.sel];
  const payload = {
    concept_code: q.code,
    records: records.filter((r) => r.code === q.code),
    now: NOW,
    staleness_window_days: 365,
    confidence_floor: 0.5,
    reference_low: q.lo, reference_high: q.hi,
    flat_band_per_day: q.flat_band_per_day ?? 0.02, flat_band_frac: q.flat_band_frac ?? 0,
  };
  const out = JSON.parse(analyze_json(JSON.stringify(payload)));
  document.getElementById("answer").innerHTML = renderAnswer(out, q);
}

function renderAnswer(out, q) {
  if (out.outcome === "abstained") {
    return `<div class="ans-card ans-abstain">
      <div class="ans-h">✗ I don't have that yet</div>
      <p>${out.message}</p>
      <p class="cite">→ ${out.suggested_action}</p>
      <div class="disclaimer">Helix abstains instead of guessing — this is a feature, not a failure.</div>
    </div>`;
  }
  const a = out; // answered, fields flattened
  if (a.escalation && a.escalation.level === "critical") {
    return `<div class="ans-card ans-escalate">
      <div class="ans-h">⚠ This needs a clinician now</div>
      <p>${a.escalation.message}</p>
      <div class="disclaimer">Optimization tips are suppressed when a red-flag value fires (ADR-009). Augments, never replaces, your clinician.</div>
    </div>`;
  }
  const tr = a.trend;
  const dir = { rising: "trending up", falling: "trending down", flat: "stable" }[tr.direction];
  const claim = a.claims[0];
  const cites = claim.evidence
    .map((e) => `<div class="cite">• ${e.concept} ${e.value} ${e.unit} — ${e.source}, ${fmtDate(e.measured_at)}</div>`)
    .join("");
  const pct = tr.percent_change != null ? ` (${(tr.percent_change * 100).toFixed(0)}% vs first reading)` : "";
  return `<div class="ans-card ans-grounded">
    <div class="ans-h">✓ Grounded answer</div>
    <p>${claim.text}</p>
    ${cites}
    <p class="cite">trend: ${dir}${pct} · ${tr.sample_size} readings${tr.crossings.length ? " · crossed reference range" : ""}</p>
    <span class="tier-chip">TIER 1 · YOUR DATA</span>
    ${a.recommendation ? `<p style="margin-top:10px">${a.recommendation.text}</p>` : ""}
    <div class="disclaimer">Not a diagnosis · every claim traces to a dated source you can open.</div>
  </div>`;
}

// ---- Records ----
function renderRecords() {
  const body = document.getElementById("records-body");
  body.innerHTML = "";
  // Thousands of daily readings → group by concept, show the latest + a count.
  const groups = new Map();
  records.forEach((r) => {
    const key = (r.code || r.concept) + "|" + r.source;
    const g = groups.get(key);
    if (!g) groups.set(key, { latest: r, count: 1 });
    else { g.count++; if (r.measured_at > g.latest.measured_at) g.latest = r; }
  });
  const rows = [...groups.values()].sort((a, b) =>
    a.latest.source.localeCompare(b.latest.source) || a.latest.concept.localeCompare(b.latest.concept));
  document.getElementById("records-count").textContent =
    `${rows.length} concepts · ${records.length.toLocaleString()} readings`;
  rows.forEach(({ latest: r, count }) => {
    const tr = document.createElement("tr");
    const rr = r.reference_range;
    const range = rr && (rr.low != null || rr.high != null) ? `${rr.low ?? "·"}–${rr.high ?? "·"}` : "—";
    tr.innerHTML = `<td>${r.concept}</td><td>${r.value} ${r.unit}</td>
      <td>${fmtDate(r.measured_at)}</td><td>${r.source}</td>
      <td>${range}</td><td>${count.toLocaleString()}</td>`;
    body.appendChild(tr);
  });
  document.getElementById("add-record").onclick = () => openModal(addRecordModal());
}

// ---- Sources ----
function renderSources() {
  const sources = [
    { n: "Apple Watch / Apple Health", s: "connected", d: "Sleep stages, resting HR, HRV, steps, SpO₂, workouts" },
    { n: "Lose It", s: "connected", d: "Daily calories + protein / carbs / fat" },
    { n: "RENPHO smart scale", s: "connected", d: "~50-metric body composition (weight, body-fat %, segmental)" },
    { n: "Quest Diagnostics", s: "connected", d: "CBC, CMP, lipids, iron studies, vitamin D, A1c, hs-CRP" },
    { n: "CVS Pharmacy", s: "connected", d: "Active medication list (RxNorm-coded)" },
    { n: "Helix Family Medicine (EMR)", s: "connected", d: "Clinician visit notes & remarks" },
    { n: "RuView (WiFi-CSI)", s: "live", d: "Contactless breathing/HR + fall/apnea screening — tap to run", demo: "sensing" },
    { n: "rvDNA genome", s: "live", d: "User-owned genome + pharmacogenomics — tap to run", demo: "genome" },
  ];
  const g = document.getElementById("sources-grid");
  g.innerHTML = sources
    .map((s, i) => `<div class="source" ${s.demo ? `data-demo="${s.demo}" style="cursor:pointer"` : ""} data-i="${i}"><h3>${s.n}</h3>
      <span class="st ${s.s === "live" ? "connected" : s.s}">${s.s}</span>
      <p class="muted" style="margin:10px 0 0;font-size:13px">${s.d}</p></div>`)
    .join("");
  g.querySelectorAll("[data-demo]").forEach((el) => {
    el.onclick = () => (el.dataset.demo === "sensing" ? runSensingDemo() : runGenomeDemo());
  });
}

// ---- Health report (full medical dashboard: bio-age, timeline, vitals, focus, recs) ----
function renderReport() {
  // Bio-age (ADR-034) — real PhenoAge from the persona's most-recent routine labs.
  const pheno = BIOAGE || {
    albumin_g_l: 47, creatinine_umol_l: 82, glucose_mmol_l: 5.0, crp_mg_dl: 0.11,
    lymphocyte_pct: 33, mcv_fl: 86, rdw_pct: 13.8, alk_phosphatase_u_l: 70,
    wbc_1000_ul: 5.8, age_years: 45,
  };
  const ba = JSON.parse(bioage_json(JSON.stringify(pheno))).bioage;
  const delta = ba.delta_years;
  const younger = delta < 0;
  document.getElementById("bioage").innerHTML = `
    <div class="ba-num">${ba.phenoage_years.toFixed(1)}<small style="font-size:16px;color:var(--muted2)"> yrs</small></div>
    <div class="ba-delta ${younger ? "younger" : "older"}">${younger ? "▼" : "▲"} ${Math.abs(delta).toFixed(1)} yrs ${younger ? "younger" : "older"} than your age (${ba.chronological_years})</div>
    <div class="ba-sub">Estimate from routine labs (PhenoAge) — not a diagnosis</div>`;

  // Timeline (ADR-031) — score over time from the persona's dated snapshots.
  const snap = (d, v) => ({
    at: NOW - d * DAY,
    subscores: [{ subsystem: "sleep", value: v, weight: 1, confidence: 0.9,
      drivers: [{ concept: "composite", points: v, trend: "stable", source_record: "r" }], trend: "stable" }],
  });
  const snaps = (TIMELINE.length ? TIMELINE : [{ days_before: 0, value: 75 }]).map((p) => snap(p.days_before, p.value));
  const tl = JSON.parse(timeline_json(JSON.stringify({ snapshots: snaps, flat_band: 0.001 })));
  document.getElementById("timeline").innerHTML = sparkline(tl);

  renderMeds();
  renderNotes();

  // Vitals & key markers — latest value per concept from the dossier.
  const byCode = {};
  records.forEach((r) => { if (r.code && (!byCode[r.code] || r.measured_at > byCode[r.code].measured_at)) byCode[r.code] = r; });
  document.getElementById("vitals-body").innerHTML = Object.values(byCode).map((r) => {
    const rr = r.reference_range;          // may be null (vitals/devices/derived have no range)
    const lo = rr && rr.low != null ? rr.low : null;
    const hi = rr && rr.high != null ? rr.high : null;
    const out = lo != null && r.value < lo ? "low" : hi != null && r.value > hi ? "high" : "ok";
    const col = out === "ok" ? "var(--ok)" : out === "low" ? "var(--vital2)" : "var(--warm)";
    const range = lo != null || hi != null ? `${lo ?? "·"}–${hi ?? "·"}` : `<span class="muted">—</span>`;
    return `<tr><td>${r.concept}</td><td><b>${r.value}</b> ${r.unit}</td>
      <td class="muted">${range}</td>
      <td style="color:${col};font-weight:700">${out.toUpperCase()}</td></tr>`;
  }).join("");

  // Focus areas (ADR-032) — real rules over the records.
  const focus = JSON.parse(focus_json(JSON.stringify({ records, now: NOW })));
  const fl = document.getElementById("focus-list");
  fl.innerHTML = focus.length ? focus.map((f) =>
    `<div class="focus-item"><span class="focus-dot fd-${f.severity}"></span>
      <div><div class="fi-msg">${f.message}</div>
      <div class="fi-cite">${f.reason.replace("_", " ")} · ${f.cites.length} reading(s)</div></div></div>`).join("")
    : `<div class="report-empty">Nothing needs attention right now.</div>`;

  // Updates & recommendations (ADR-033) — grounded, evidence-tiered.
  const ans = JSON.parse(analyze_json(JSON.stringify({
    concept_code: "2276-4", records: records.filter((r) => r.code === "2276-4"),
    now: NOW, staleness_window_days: 365, confidence_floor: 0.5,
    reference_low: 30, reference_high: 400, flat_band_per_day: 0.01, flat_band_frac: 0.08,
  })));
  const recs = [];
  if (ans.outcome === "answered" && ans.recommendation)
    recs.push({ tier: "TIER 1 · YOUR DATA", text: ans.recommendation.text });
  focus.forEach((f) => recs.push({ tier: "TIER 1 · YOUR DATA", text: f.message }));
  document.getElementById("recs-list").innerHTML = recs.length ? recs.map((r) =>
    `<div class="rec-item"><span class="rec-tier">${r.tier}</span>${r.text}</div>`).join("")
    : `<div class="report-empty">No new recommendations — everything's steady.</div>`;
}

// Active medications (Pharmacy domain) — RxNorm-coded, shown but never trended.
function renderMeds() {
  const el = document.getElementById("meds-list");
  if (!el) return;
  el.innerHTML = MEDS.length
    ? MEDS.map((m) => `<div class="med-item"><div class="med-name">${m.concept}</div>
        <div class="med-meta">${m.source} · RxNorm ${m.code}</div></div>`).join("")
    : `<div class="report-empty">No active medications on file.</div>`;
}

// Clinician visit notes (EMR domain) — plain-language remarks.
function renderNotes() {
  const el = document.getElementById("notes-list");
  if (!el) return;
  el.innerHTML = NOTES.length
    ? NOTES.map((n) => `<div class="note-item">
        <div class="note-top"><b>${n.kind}</b><span class="note-meta">${n.author} · ${fmtDate(n.date_ms)}</span></div>
        <p class="note-text">${n.text}</p></div>`).join("")
    : `<div class="report-empty">No clinician notes on file.</div>`;
}

// Render a small SVG sparkline for the score timeline.
function sparkline(tl) {
  const pts = tl.points;
  const w = 520, h = 90, pad = 6;
  const xs = pts.map((p) => p.at), ys = pts.map((p) => p.value);
  const x0 = Math.min(...xs), x1 = Math.max(...xs);
  const sx = (x) => pad + ((x - x0) / (x1 - x0 || 1)) * (w - 2 * pad);
  const sy = (y) => h - pad - ((y - 40) / 60) * (h - 2 * pad); // 40..100 range
  const line = pts.map((p, i) => `${i ? "L" : "M"}${sx(p.at).toFixed(1)},${sy(p.value).toFixed(1)}`).join(" ");
  const area = `${line} L${sx(x1).toFixed(1)},${h - pad} L${sx(x0).toFixed(1)},${h - pad} Z`;
  const dots = pts.map((p) => `<circle class="tl-dot" cx="${sx(p.at).toFixed(1)}" cy="${sy(p.value).toFixed(1)}" r="3"/>`).join("");
  const cp = tl.change_point_at ? `<line class="tl-cp" x1="${sx(tl.change_point_at).toFixed(1)}" y1="${pad}" x2="${sx(tl.change_point_at).toFixed(1)}" y2="${h - pad}"/>` : "";
  const dir = { rising: "▲ improving", falling: "▼ slipping", flat: "→ steady" }[tl.direction] || "";
  return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none">
    <defs><linearGradient id="tlg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#34e0c4"/><stop offset="1" stop-color="#34e0c4" stop-opacity="0"/></linearGradient></defs>
    <path class="tl-area" d="${area}"/><path class="tl-line" d="${line}"/>${cp}${dots}
  </svg><div class="tl-cap">${dir} · ${pts.length} points${tl.change_point_at ? " · change-point detected" : ""}</div>`;
}

// ---- Import (FHIR / OCR image / CSV → real records into the live dossier) ----
let importedCount = 0;

// Fill a population reference-range fallback (NHANES, helix-refranges) for records
// that arrived without one — labeled so it never reads as the lab's own range.
function fillPopRanges(recs) {
  recs.forEach((r) => {
    const rr = r.reference_range;
    const hasRange = rr && (rr.low != null || rr.high != null);
    if (!hasRange && r.code) {
      const pop = JSON.parse(population_range_json(r.code));
      if (pop) {
        r.reference_range = { low: pop.low, high: pop.high };
        r.range_source = "population"; // tag for honest labeling
      }
    }
  });
}

function addImportedRecords(recs, badge = "imported") {
  fillPopRanges(recs);
  recs.forEach((r) => records.push(r));
  importedCount += recs.length;
  // re-render everything that consumes records
  renderRecords();
  renderReport();
  const log = document.getElementById("import-log");
  if (importedCount === recs.length) log.innerHTML = "";
  recs.forEach((r) => {
    const div = document.createElement("div");
    div.className = "imp-row";
    div.innerHTML = `<span>${r.concept} <b>${r.value}</b> ${r.unit}
      <span class="imp-src">· ${r.source}${r.code ? " · " + r.code : ""}</span></span>
      <span class="imp-badge imp-ok">${badge}</span>`;
    log.appendChild(div);
  });
  document.getElementById("import-count").textContent = `· ${importedCount} value(s)`;
}
function logQueued(label, reason) {
  const log = document.getElementById("import-log");
  const div = document.createElement("div");
  div.className = "imp-row";
  div.innerHTML = `<span>${label} <span class="imp-src">· held: ${reason.replace(/_/g, " ")}</span></span>
    <span class="imp-badge imp-queue">review</span>`;
  log.appendChild(div);
}

const SAMPLE_FHIR = JSON.stringify({
  resourceType: "Bundle",
  entry: [
    { resource: { resourceType: "Observation", id: "hdl1",
      code: { coding: [{ system: "http://loinc.org", code: "2085-9", display: "HDL Cholesterol" }] },
      valueQuantity: { value: 58, unit: "mg/dL" }, effectiveDateTime: "2026-06-10",
      referenceRange: [{ low: { value: 40 }, high: { value: 100 } }] } },
    { resource: { resourceType: "Observation", id: "tsh1",
      code: { coding: [{ system: "http://loinc.org", code: "3016-3", display: "TSH" }] },
      valueQuantity: { value: 2.1, unit: "mIU/L" }, effectiveDateTime: "2026-06-10",
      referenceRange: [{ low: { value: 0.4 }, high: { value: 4.0 } }] } },
  ],
}, null, 2);
const SAMPLE_CSV = "Vitamin B12, 2132-9, 540, pg/mL, 200, 900\nHbA1c, 4548-4, 5.4, %, 4.0, 5.6";
const SAMPLE_APPLE = `<?xml version="1.0"?>
<HealthData>
 <Record type="HKQuantityTypeIdentifierRestingHeartRate" unit="count/min" startDate="2026-06-20 06:00:00 +0000" value="54"/>
 <Record type="HKQuantityTypeIdentifierHeartRateVariabilitySDNN" unit="ms" startDate="2026-06-20 06:00:00 +0000" value="48"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" unit="kg" startDate="2026-06-21 08:00:00 +0000" value="72.5"/>
 <Record type="HKQuantityTypeIdentifierOxygenSaturation" unit="%" startDate="2026-06-21 23:00:00 +0000" value="97"/>
</HealthData>`;
const SAMPLE_GENOME = `# 23andMe raw data file
# rsid\tchromosome\tposition\tgenotype
rs4477212\t1\t82154\tAA
rs4244285\t10\t96541616\tAG
rs1801133\t1\t11856378\tCT
rs4988235\t2\t136608646\tGG`;

function wireImport() {
  document.getElementById("fhir-in").value = SAMPLE_FHIR;
  document.getElementById("csv-in").value = SAMPLE_CSV;

  // ① FHIR
  document.getElementById("fhir-import").onclick = () => importFhir(document.getElementById("fhir-in").value);
  document.getElementById("fhir-file").onchange = (e) => {
    const f = e.target.files[0]; if (!f) return;
    const r = new FileReader();
    r.onload = () => { document.getElementById("fhir-in").value = r.result; importFhir(r.result); };
    r.readAsText(f);
  };

  // ② OCR image
  const drop = document.getElementById("ocr-drop");
  const fileIn = document.getElementById("ocr-file");
  drop.ondragover = (e) => { e.preventDefault(); drop.classList.add("drag"); };
  drop.ondragleave = () => drop.classList.remove("drag");
  drop.ondrop = (e) => { e.preventDefault(); drop.classList.remove("drag"); if (e.dataTransfer.files[0]) ocrImage(e.dataTransfer.files[0]); };
  fileIn.onchange = (e) => { if (e.target.files[0]) ocrImage(e.target.files[0]); };

  // ③ CSV
  document.getElementById("csv-import").onclick = () => importCsv(document.getElementById("csv-in").value);

  // ④ Apple Health export.xml  ·  ⑤ 23andMe raw .txt
  wireDrop("apple-drop", "apple-file", importApple);
  wireDrop("geno-drop", "geno-file", importGenome);
}

// Wire a dropzone + hidden file input to a text handler.
function wireDrop(dropId, fileId, handler) {
  const drop = document.getElementById(dropId);
  const fileIn = document.getElementById(fileId);
  const read = (f) => { const r = new FileReader(); r.onload = () => handler(r.result, f.name); r.readAsText(f); };
  drop.ondragover = (e) => { e.preventDefault(); drop.classList.add("drag"); };
  drop.ondragleave = () => drop.classList.remove("drag");
  drop.ondrop = (e) => { e.preventDefault(); drop.classList.remove("drag"); if (e.dataTransfer.files[0]) read(e.dataTransfer.files[0]); };
  fileIn.onchange = (e) => { if (e.target.files[0]) read(e.target.files[0]); };
}

function importApple(xml, name) {
  const status = document.getElementById("apple-status");
  try {
    const recs = JSON.parse(apple_health_import_json(xml, "Apple Health"));
    if (recs.length) { addImportedRecords(recs, "Apple Health"); status.innerHTML = `<span class="ok">✓ ${recs.length} record(s) from ${name || "export.xml"}</span>`; }
    else status.innerHTML = `<span class="warn">No recognized HealthKit records found.</span>`;
  } catch (e) { status.innerHTML = `<span class="warn">Couldn't parse that file: ${e.message}</span>`; }
}

function importGenome(text, name) {
  const status = document.getElementById("geno-status");
  try {
    const r = JSON.parse(genome_raw_import_json(text, name || "23andMe"));
    if (r.records.length) addImportedRecords(r.records, "Genome");
    const findings = r.findings.map((f) => `${f.gene} ${f.label}: ${f.genotype} (${f.effect_allele_copies} copy)`).join("; ");
    status.innerHTML = r.findings.length
      ? `<span class="ok">✓ ${r.total_variants.toLocaleString()} variants scanned · ${r.findings.length} finding(s)</span><div class="muted small" style="margin-top:6px">${findings}</div><div class="muted small" style="margin-top:4px">${r.caveat}</div>`
      : `<span class="warn">${r.total_variants.toLocaleString()} variants scanned · no annotated SNPs in this file.</span>`;
  } catch (e) { status.innerHTML = `<span class="warn">Couldn't parse that file: ${e.message}</span>`; }
}

function importFhir(text) {
  try {
    const out = JSON.parse(fhir_import_json(text, "Imported FHIR"));
    if (out.records.length) addImportedRecords(out.records, "FHIR");
    if (out.queued) logQueued(`${out.queued} FHIR resource(s)`, "unparseable");
    if (!out.records.length && !out.queued) flashImport("No Observations found in that bundle.");
  } catch (e) { flashImport("Couldn't parse that JSON: " + e.message); }
}

function importCsv(text) {
  const recs = [];
  text.split(/\n+/).forEach((line) => {
    const p = line.split(",").map((s) => s.trim());
    if (p.length < 4 || !p[0]) return;
    const [concept, code, value, unit, lo, hi] = p;
    const v = parseFloat(value);
    if (!isFinite(v)) return;
    recs.push({
      id: `csv-${concept}-${Date.now()}-${recs.length}`, source: "Manual / CSV",
      measured_at: NOW, method: "manual_entry", code: code || null, concept, value: v, unit: unit || "",
      reference_range: { low: lo ? parseFloat(lo) : null, high: hi ? parseFloat(hi) : null },
      confidence: 0.8,
    });
  });
  if (recs.length) addImportedRecords(recs, "CSV"); else flashImport("No valid rows parsed.");
}

// Thumbnail + perceptual fingerprint (helix-visual) for a dropped image. Returns
// a short "looks like" note comparing it to previously-imported images.
async function visualPreview(file) {
  const prev = document.getElementById("ocr-preview");
  const img = new Image();
  const url = URL.createObjectURL(file);
  await new Promise((res, rej) => { img.onload = res; img.onerror = rej; img.src = url; });
  // downscale to a small grayscale buffer for the perceptual encoder
  const W = 96, H = Math.max(1, Math.round((img.height / img.width) * 96));
  const cv = document.createElement("canvas");
  cv.width = W; cv.height = H;
  const ctx = cv.getContext("2d");
  ctx.drawImage(img, 0, 0, W, H);
  const rgba = ctx.getImageData(0, 0, W, H).data;
  const gray = new Uint8Array(W * H);
  for (let i = 0; i < W * H; i++) gray[i] = (0.299 * rgba[i * 4] + 0.587 * rgba[i * 4 + 1] + 0.114 * rgba[i * 4 + 2]) | 0;
  prev.innerHTML = `<img class="ocr-thumb" src="${url}" alt="preview"/><div class="ocr-vis" id="ocr-vis">perceptual fingerprint…</div>`;
  let note = "";
  try {
    const emb = visual_encode_json(W, H, gray);
    let best = 0, bestName = "";
    for (const m of visualMemory) {
      const s = visual_maxsim_json(emb, m.emb);
      if (s > best) { best = s; bestName = m.name; }
    }
    visualMemory.push({ name: file.name || "image", emb });
    note = bestName
      ? `🔎 visually ${Math.round(best * 100)}% similar to “${bestName}”`
      : `🔎 visual fingerprint captured (${visualMemory.length === 1 ? "first image" : "no prior match"})`;
    document.getElementById("ocr-vis").textContent = note;
  } catch (e) { document.getElementById("ocr-vis").textContent = "visual fingerprint unavailable"; }
  return url;
}

// In-browser OCR of a lab image (tesseract.js from CDN), then the helix-ocr safety gate.
async function ocrImage(file) {
  const status = document.getElementById("ocr-status");
  status.innerHTML = "Loading on-device OCR…";
  let url;
  try {
    url = await visualPreview(file); // thumbnail + helix-visual fingerprint
    const { default: Tesseract } = await import("https://esm.sh/tesseract.js@5");
    status.innerHTML = "Reading the image…";
    const { data } = await Tesseract.recognize(url, "eng");
    URL.revokeObjectURL(url);
    const candidates = extractAnalytes(data.text);
    if (!candidates.length) { status.innerHTML = `<span class="warn">No values found in that image.</span>`; return; }
    const doc = { doc_label: file.name || "lab-image", imported_at: NOW, candidates };
    const gated = JSON.parse(ocr_ingest_json(JSON.stringify(doc), 0.5));
    // `Gated` is internally tagged: an accepted item spreads the ProvRecord fields
    // onto the object alongside status:"accepted". Strip status → the record.
    const accepted = gated.filter((g) => g.status === "accepted").map(({ status, ...rec }) => rec);
    let queued = 0;
    gated.forEach((g) => { if (g.status === "queued") { queued++; logQueued(g.candidate.label, g.reason); } });
    if (accepted.length) addImportedRecords(accepted, "OCR");
    status.innerHTML = `<span class="ok">✓ ${accepted.length} value(s) imported</span>${queued ? ` · <span class="warn">${queued} held for review</span>` : ""}`;
  } catch (e) {
    status.innerHTML = `<span class="warn">OCR unavailable here (${e.message}). Try the CSV paste instead.</span>`;
  }
}

// Naive analyte extraction: lines like "Ferritin 28 ng/mL  (30-400)".
function extractAnalytes(text) {
  const out = [];
  text.split(/\n+/).forEach((line) => {
    const m = line.match(/^([A-Za-z][A-Za-z0-9 \-]{1,30}?)\s+(-?\d+(?:\.\d+)?)\s*([A-Za-z%\/µ]+(?:\/[A-Za-z]+)?)?/);
    if (!m) return;
    const rr = line.match(/(\d+(?:\.\d+)?)\s*[-–]\s*(\d+(?:\.\d+)?)/);
    out.push({
      label: m[1].trim(), value: parseFloat(m[2]), unit: (m[3] || "").trim(),
      reference_low: rr ? parseFloat(rr[1]) : null, reference_high: rr ? parseFloat(rr[2]) : null,
      ocr_confidence: 0.9,
    });
  });
  return out;
}

function flashImport(msg) {
  const log = document.getElementById("import-log");
  log.innerHTML = `<div class="report-empty">${msg}</div>`;
}

// Run a sample RuView WiFi-CSI reading through the real wasm adapter (ADR-020).
function runSensingDemo() {
  const reading = {
    node_id: "esp-bedroom", room: "bedroom", recorded_at: NOW,
    vitals: { breathing_bpm: 14.2, heart_rate_bpm: 61 },
    states: ["someone-sleeping", "apnea-screening", "possible-distress"],
    witness_signature: "ed25519:demo",
  };
  const out = JSON.parse(sensing_reading_json(JSON.stringify(reading)));
  const recs = out.records
    .map((r) => `<div class="cite">• ${r.concept} ${r.value} ${r.unit} — ${r.source} · conf ${r.confidence}</div>`)
    .join("");
  const flags = out.flags
    .map((f) => `<div class="bd-row"><span>${f.state} <span class="muted">(${f.room})</span></span><b style="color:${f.level === "critical" ? "#fb7185" : "#f6c177"}">${f.level}</b></div>`)
    .join("");
  openModal(`<h2>RuView WiFi-CSI · live</h2>
    <p class="muted">Contactless vitals extracted on-device, mapped through the real Rust adapter (ADR-020).</p>
    <div style="margin:12px 0">${recs}</div>
    <div class="muted" style="font-size:11.5px;letter-spacing:1px;font-weight:700">ESCALATION SCREENING FLAGS</div>
    ${flags}
    <p class="disclaimer" style="margin-top:12px">Screening only, not a diagnosis. Safety flags route to the Escalation Guardian (ADR-009).</p>`);
}

// Run a sample genome profile through the real wasm adapter (ADR-021).
function runGenomeDemo() {
  const profile = {
    source_file: "23andMe-v5", imported_at: NOW, genotype_count: 640000,
    pharmaco: [
      { gene: "CYP2D6", diplotype: "*4/*4", phenotype: "poor" },
      { gene: "CYP2C19", diplotype: "*1/*1", phenotype: "normal" },
    ],
    risks: [{ trait_name: "Type 2 diabetes", score: 0.62, band: "elevated" }],
    ancestry_caveat: "primarily European reference panel",
  };
  const out = JSON.parse(genome_profile_json(JSON.stringify(profile)));
  const recs = out.records
    .map((r) => `<div class="cite">• ${r.concept} — ${r.unit} · conf ${r.confidence}</div>`)
    .join("");
  const adv = out.advisories
    .map((a) => `<p style="margin:6px 0;font-size:13px">⚕ ${a.message}</p>`)
    .join("");
  openModal(`<h2>rvDNA genome · live</h2>
    <p class="muted">User-owned genome analyzed on-device, mapped through the real Rust adapter (ADR-021).</p>
    <div style="margin:12px 0">${recs}</div>
    ${adv}
    <p class="disclaimer" style="margin-top:8px">${out.privacy_note}</p>
    <p class="disclaimer">Decision-support, not a diagnosis — verify with your prescriber.</p>`);
}

// ---- Nav ----
function wireNav() {
  const titles = {
    dashboard: ["Dashboard", "Your body, assembled into one living dossier."],
    report: ["Health report", "Score over time, vitals, focus areas, and your biological age."],
    ask: ["Ask Helix", "Answered only from your data — with citations."],
    records: ["Records", "Every value, sourced and dated."],
    import: ["Import", "Bring in records, lab images, and values — parsed on-device."],
    sources: ["Data sources", "Connect everything; it just works."],
  };
  document.querySelectorAll(".nav-item").forEach((btn) => {
    btn.onclick = () => {
      document.querySelectorAll(".nav-item").forEach((b) => b.classList.remove("active"));
      btn.classList.add("active");
      const v = btn.dataset.view;
      document.querySelectorAll(".view").forEach((s) => s.classList.toggle("hidden", s.dataset.view !== v));
      document.getElementById("view-title").textContent = titles[v][0];
      document.getElementById("view-sub").textContent = titles[v][1];
    };
  });
}

// ---- Modals ----
function wireModals() {
  document.getElementById("modal-close").onclick = closeModal;
  document.getElementById("modal-host").onclick = (e) => { if (e.target.id === "modal-host") closeModal(); };
  document.getElementById("open-guide").onclick = () => openModal(guideModal());
  document.getElementById("open-score-breakdown").onclick = () => openModal(breakdownModal());
  document.querySelectorAll("[data-modal='score-info']").forEach((el) => (el.onclick = () => openModal(scoreInfoModal())));
  document.querySelectorAll("[data-modal='bioage-info']").forEach((el) => (el.onclick = () => openModal(bioageInfoModal())));
}

function bioageInfoModal() {
  return `<h2>About biological age</h2>
    <p>Computed with the peer-reviewed <b>PhenoAge</b> algorithm (Levine et al., 2018) from <b>9 routine
    blood markers</b> + your age — no special test required.</p>
    <p>It's an <b>estimate of how your labs compare to typical aging — not a measurement and not a
    diagnosis</b>. The headline is the <i>difference</i> from your calendar age; it's population-derived
    (ancestry-dependent). Discuss with a clinician.</p>
    <p class="muted" style="font-size:12.5px;margin-top:10px">Computed deterministically in Rust/WASM (helix-bioage, ADR-034).</p>`;
}
function openModal(html) {
  document.getElementById("modal-content").innerHTML = html;
  document.getElementById("modal-host").classList.remove("hidden");
}
function closeModal() { document.getElementById("modal-host").classList.add("hidden"); }

function guideModal() {
  return `<h2>Get started in 4 steps</h2>
    <p>Helix turns scattered records into one interrogable dossier — grounded, private, and visual.</p>
    <ol class="steps">
      <li><h4>Connect your sources</h4><p>EMR, labs, wearables, genome, and the Cognitum Seed flow into one encrypted, on-device vault.</p></li>
      <li><h4>Helix normalizes everything</h4><p>Every value is mapped to LOINC/RxNorm/SNOMED with provenance, units, and a reference range attached.</p></li>
      <li><h4>Ask anything</h4><p>Answers are built only from your data, computed deterministically, and verified before you see them. No data → an honest "I don't have that."</p></li>
      <li><h4>See and act</h4><p>A decomposable 0–100 score and body-system view show where you stand and which way you're heading — with a clear next step.</p></li>
    </ol>`;
}
function scoreInfoModal() {
  return `<h2>About the health score</h2>
    <p>A single 0–100 number that is <b>fully decomposable</b> — never a black box. It is a weighted
    roll-up of subsystem sub-scores, each tracing to the exact measurements that drove it. It is a
    <b>wellness orientation aid, not a medical risk diagnosis</b>.</p>
    <p class="muted" style="margin-top:10px;font-size:12.5px">Methodology: ${score.methodology_version} · computed in Rust/WASM (helix-score).</p>`;
}
function breakdownModal() {
  const rows = score.subscores
    .map((s) => `<div class="bd-row"><span>${cap(s.subsystem)} <span class="muted">(${(s.weight * 100).toFixed(0)}% weight, ${(s.confidence * 100).toFixed(0)}% conf · ${s.trend})</span></span><b>${s.value}</b></div>`)
    .join("");
  return `<h2>Score breakdown</h2><p class="muted">${score.disclaimer}</p>
    <div style="margin-top:14px">${rows}
    <div class="bd-row" style="border-top:2px solid var(--vital2)"><b>Composite</b><b>${score.value} / 100</b></div></div>`;
}
function openSystemModal(s) {
  openModal(`<h2>${cap(s.subsystem)}</h2>
    <p>Sub-score <b>${s.value}/100</b> · ${(s.weight * 100).toFixed(0)}% of composite · trend ${s.trend}.</p>
    <p class="muted">Driven by: ${s.driver}. Each driver links to a dated source record (ADR-005).</p>`);
}
function addRecordModal() {
  return `<h2>Add a record</h2>
    <p class="muted">In the full app this imports from a connector or a lab PDF (OCR). For this demo, records
    are seeded so you can see the pipeline run end to end.</p>
    <p class="muted" style="font-size:12.5px;margin-top:10px">Every added value gets provenance, units, and a
    reference range before it can be used in an answer.</p>`;
}

// ---- utils ----
function cap(s) { return s.charAt(0).toUpperCase() + s.slice(1); }
function fmtDate(ms) { const d = new Date(ms); return `${d.toLocaleString("en", { month: "short" })} ${d.getDate()} ${d.getFullYear()}`; }

boot();
